// FORGE — PH-PPL Program Data Configuration
// ============================================
// This file contains ALL exercise definitions, warm-ups, tips, and video links.
// To add, remove, or modify exercises: edit this file only. No other code changes needed.
// To add a new exercise: copy an existing exercise block and modify the fields.
// To remove an exercise: delete its block from the exercises array.

const FORGE_DATA = {
  version: "1.0.0",
  programName: "PH-PPL",
  // Sheets addresses live in js/config.js (v0.22), so copies differ by one file.
  sheetsWebhookUrl: (typeof FORGE_CONFIG !== 'undefined' && FORGE_CONFIG.sheetsWebhookUrl) || '',
  sheetsViewUrl: (typeof FORGE_CONFIG !== 'undefined' && FORGE_CONFIG.sheetsViewUrl) || '',
  // Six training slots. Rest is NO LONGER a cycle position: it is a calendar
  // marker only, so marking a rest day never costs you a workout. "code" is
  // what the calendar prints: P/B/L for push/back/legs, 1/2 for the power and
  // hypertrophy variants. C is reserved for the Back & Core alternate.
  cycleDays: [
    { id: "push-a", name: "Push A", type: "power", label: "Power", color: "amber", code: "P1" },
    { id: "pull-a", name: "Pull A", type: "power", label: "Power", color: "amber", code: "B1" },
    { id: "legs-a", name: "Legs A", type: "power", label: "Power", color: "amber", code: "L1" },
    { id: "push-b", name: "Push B", type: "hypertrophy", label: "Hypertrophy", color: "cyan", code: "P2" },
    { id: "pull-b", name: "Pull B", type: "hypertrophy", label: "Hypertrophy", color: "cyan", code: "B2" },
    { id: "legs-b", name: "Legs B", type: "hypertrophy", label: "Hypertrophy", color: "cyan", code: "L2" }
  ],

  // Alternate days (light / calisthenics / back-core) land here in Phase 4.
  // deriveCycleIndex() and dayById() already read this shape.
  alternates: {
    "cal-push": { id: "cal-push", name: "Calisthenics Push", type: "calisthenics", label: "Bodyweight", color: "green", code: "CP", advancesByDefault: true },
    "cal-pull": { id: "cal-pull", name: "Calisthenics Pull", type: "calisthenics", label: "Bodyweight", color: "green", code: "CB", advancesByDefault: true },
    "cal-legs": { id: "cal-legs", name: "Calisthenics Legs", type: "calisthenics", label: "Bodyweight", color: "green", code: "CL", advancesByDefault: true },
    "cal-full": { id: "cal-full", name: "Calisthenics Full Body", type: "calisthenics", label: "Bodyweight", color: "green", code: "CF", advancesByDefault: true },
    "back-core": { id: "back-core", name: "Back & Core", type: "power", label: "Posterior & Core", color: "violet", code: "C", advancesByDefault: false }
  },

  // RPE descriptions for reference tooltips
  rpeGuide: {
    7: "Could do 3 more reps",
    8: "Could do 2 more reps",
    9: "Could do 1 more rep",
    10: "Nothing left"
  },

  // Progression rules displayed in settings/info
  progressionRules: {
    power: "When you complete all prescribed sets and reps at RPE 7-8, add the smallest weight increment available next session.",
    hypertrophy: "Work the rep range from bottom to top. When you hit the top of the range across all sets, add weight and reset to the bottom of the range."
  },

  workouts: {
    // =========================================================
    // PUSH A — POWER
    // =========================================================
    "push-a": {
      id: "push-a",
      name: "Push A",
      type: "power",
      label: "Power",
      goal: "Strength — heavy compounds, low reps, long rest",
      estimatedMinutes: 62,
      minutesBySize: { light: 30, normal: 62, extended: 88 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Arm circles, 10 forward and 10 back",
          "Band pull-aparts, 15 reps with a light band, squeezing shoulder blades",
          "Push-up walkouts, 5 reps, walking hands out slowly into full push-up position",
          "Empty bar or light dumbbell bench press, 10-12 easy reps to groove the pattern"
        ]
      },
      exercises: [
        {
          id: "explosive-pushup",
          name: "Explosive Push-Ups",
          tier: 2,
          sets: 2,
          reps: "to failure",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          image: "explosive-pushup.png",
          video: "https://www.youtube.com/watch?v=bCBFRCKjJME",
          tip: "Standard push-ups with maximum speed on the concentric. If you can clap, clap. If not, just press as explosively as possible. Power intent, not grinding reps.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Building toward handstand push-ups. Explosive push-ups develop pressing power."
        },
        {
          id: "bb-flat-bench",
          name: "Barbell Flat Bench Press",
          tier: 1,
          sets: 4,
          reps: "5",
          rpe: "7-8",
          rest: 70, // seconds
          restLabel: "70 sec",
          weightMode: "free", // free | bw | bw-plus | bw-minus
          image: "bb-flat-bench.png",
          video: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
          tip: "Plant the feet, retract the shoulder blades, control the descent to chest, drive through the floor on the press. This is your primary strength marker for pressing. Track it religiously.",
          isFinisher: false
        },
        {
          id: "bb-overhead-press",
          name: "Standing Barbell OHP",
          tier: 1,
          sets: 4,
          reps: "5",
          rpe: "7-8",
          rest: 70,
          restLabel: "70 sec",
          weightMode: "free",
          image: "bb-overhead-press.png",
          video: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
          tip: "Brace the core hard before each rep. Slight lean back is fine, but the bar path should travel straight up over the crown of the head. No leg drive. Strict press.",
          isFinisher: false
        },
        {
          id: "incline-bb-press",
          name: "Incline Barbell Press",
          sets: 3,
          reps: "6-8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 3,
          image: "incline-bb-press.png",
          video: "https://www.youtube.com/results?search_query=incline+barbell+bench+press+form",
          tip: "Bench at 30 degrees, not 45. Higher than that and it becomes a shoulder press with extra steps. Same setup as flat bench: shoulder blades pinned, feet planted, bar to the upper chest just below the collarbone.",
          isFinisher: false
        },
        {
          id: "weighted-dips-a",
          name: "Weighted Dips",
          tier: 2,
          sets: 3,
          reps: "6-8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw-plus",
          image: "weighted-dips.png",
          video: "https://www.youtube.com/watch?v=2z8JmcrW-As",
          tip: "Use a belt or hold a dumbbell between the feet. Slight forward lean to keep emphasis on chest and triceps. Full depth, elbows to roughly 90 degrees. If bodyweight dips aren't at 8+ clean reps yet, stay unweighted.",
          isFinisher: false
        },
        {
          id: "cg-bench-press",
          name: "Close-Grip Bench Press",
          tier: 2,
          sets: 3,
          reps: "8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "cg-bench-press.png",
          video: "https://www.youtube.com/watch?v=nEF0bv2FW94",
          tip: "Hands roughly shoulder width. Tuck the elbows slightly. This is both a tricep builder and a bench press accessory. Controlled descent, no bouncing.",
          isFinisher: false
        },
        {
          id: "back-extension",
          name: "Back Extension",
          sets: 3,
          reps: "12-15",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "back-extension.png",
          video: "https://www.youtube.com/results?search_query=45+degree+back+extension+proper+form",
          tip: "Log 0 until bodyweight is easy for 3 sets of 15, then hold a plate to the chest. Hinge at the hips, not the spine. Rise until the body is a straight line and STOP. Hyperextending past that is how you turn a prehab exercise into the thing that hurt you.",
          isFinisher: false
        },
        {
          id: "cable-crunch",
          name: "Cable Crunch",
          sets: 3,
          reps: "15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "cable-crunch.png",
          video: "https://www.youtube.com/results?search_query=cable+crunch+proper+form+abs",
          tip: "Kneel facing the stack, rope beside the ears, hips locked in place. Curl the ribcage toward the pelvis. The hips must not move. If you are bowing at the hips it is a lat pulldown for your abs and does nothing.",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head actually moving. Hold 10 seconds. Repeat on the back of the head, then each side. That is one set. No load, no motion, no momentum. This builds tolerance before any weight goes near the neck.",
          isFinisher: false
        }
      ]
    },

    // =========================================================
    // PULL A — POWER
    // =========================================================
    "pull-a": {
      id: "pull-a",
      name: "Pull A",
      type: "power",
      label: "Power",
      goal: "Strength — heavy compounds, low reps, long rest",
      estimatedMinutes: 60,
      minutesBySize: { light: 30, normal: 60, extended: 85 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Band pull-aparts, 15 reps",
          "Cat-cow stretches, 8 slow reps through full spinal range",
          "Thoracic rotations from half-kneeling, 8 each side",
          "Light lat pulldowns or light dumbbell rows, 10 reps to wake up the lats"
        ]
      },
      exercises: [
        {
          id: "bb-bent-row",
          name: "Barbell Bent-Over Row",
          tier: 1,
          sets: 4,
          reps: "5",
          rpe: "7-8",
          rest: 70,
          restLabel: "70 sec",
          weightMode: "free",
          image: "bb-bent-row.png",
          video: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
          tip: "Hinge at the hips, torso at roughly 45 degrees, pull the bar to the lower chest. A small amount of body english is fine on the last rep or two, but this should be mostly strict. Squeeze the shoulder blades at the top.",
          isFinisher: false
        },
        {
          id: "weighted-pullup",
          name: "Weighted Pull-Ups",
          tier: 1,
          sets: 4,
          reps: "5-6",
          rpe: "8",
          rest: 70,
          restLabel: "70 sec",
          weightMode: "bw-plus",
          image: "weighted-pullup.png",
          video: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
          tip: "Full dead hang at the bottom, chin over bar at the top. Use a belt for added weight. If bodyweight pull-ups aren't solid at 6+ reps yet, do heavy lat pulldowns at the same rep scheme instead.",
          isFinisher: false
        },
        {
          id: "chest-supported-row",
          name: "Chest-Supported Row",
          sets: 3,
          reps: "10",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 2,
          image: "chest-supported-row.png",
          video: "https://www.youtube.com/results?search_query=chest+supported+row+form",
          tip: "Chest pinned to the pad, which takes the lower back out entirely. That is the point: all the pulling volume, none of the spinal load you already paid for on bent-over rows. Pull to the lower ribs, squeeze, control back.",
          isFinisher: false
        },
        {
          id: "bb-shrugs",
          name: "Barbell Shrugs",
          tier: 1,
          sets: 3,
          reps: "8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "bb-shrugs.png",
          video: "https://www.youtube.com/watch?v=cJRVVxmytaM",
          tip: "Heavy. Hold at the top for a one-count. Straight up and down, no rolling the shoulders.",
          isFinisher: false
        },
        {
          id: "bb-curls",
          name: "Barbell Curls",
          tier: 2,
          sets: 3,
          reps: "8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "bb-curls.png",
          video: "https://www.youtube.com/watch?v=kwG2ipFRgFo",
          tip: "Strict. If the torso is swaying, the weight is too heavy. Curls on power day are heavier and lower rep than most people do them. Treat them like a real lift.",
          isFinisher: false
        },
        {
          id: "preacher-curl",
          name: "Preacher Curl",
          sets: 3,
          reps: "10-12",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "preacher-curl.png",
          video: "https://www.youtube.com/results?search_query=preacher+curl+proper+form",
          tip: "Armpits into the top of the pad. Do not let the elbows drift down the slope. Full extension at the bottom, which is the whole reason to use this over standing curls, so resist the urge to cut the range short.",
          isFinisher: false
        },
        {
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "hanging-leg-raise.png",
          video: "https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form",
          tip: "Start with knees tucked if straight legs make you swing. The goal is curling the pelvis up at the top, not just lifting the legs. No swinging. If you are using momentum, drop to bent knees and rebuild it.",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head actually moving. Hold 10 seconds. Repeat on the back of the head, then each side. That is one set. No load, no motion, no momentum. This builds tolerance before any weight goes near the neck.",
          isFinisher: false
        },
        {
          id: "dead-hang",
          name: "Dead Hangs",
          tier: 2,
          sets: 2,
          reps: "max time",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          image: "dead-hang.png",
          video: "https://www.youtube.com/watch?v=wPmGMqaKhJo",
          tip: "Full grip, shoulders engaged (not shrugging up to the ears). Track your times. When consistently over 60 seconds, start adding scapular pulls from the hang for sets of 8-10.",
          trackMode: "time",
          isFinisher: true,
          finisherProgression: "Building toward advanced pull-up variations. Dead hangs develop grip endurance and scapular stability."
        }
      ]
    },

    // =========================================================
    // LEGS A — POWER
    // =========================================================
    "legs-a": {
      id: "legs-a",
      name: "Legs A",
      type: "power",
      label: "Power",
      goal: "Strength — heavy compounds, low reps, long rest",
      estimatedMinutes: 58,
      minutesBySize: { light: 30, normal: 58, extended: 82 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Leg swings front to back, 10 each leg",
          "Lateral leg swings, 10 each",
          "Bodyweight squats, 10 slow reps focusing on depth",
          "Walking lunges, 8 each leg",
          "Hip circles (standing, big circles with the knee), 8 each direction per leg"
        ]
      },
      exercises: [
        {
          id: "kb-swings",
          name: "Kettlebell Swings",
          sets: 3,
          reps: "15",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 2,
          image: "kb-swings.png",
          video: "https://www.youtube.com/results?search_query=kettlebell+swing+hip+hinge+tutorial",
          tip: "Hip hinge, not a squat. The bell is thrown forward by the hips snapping, arms are just rope. Bell floats to chest height, no higher. Done right you will feel this in the glutes and hamstrings, which is exactly what you want awake before heavy squats.",
          isFinisher: false,
          isPrimer: true
        },
        {
          id: "bb-back-squat",
          name: "Barbell Back Squat",
          tier: 1,
          sets: 4,
          reps: "5",
          rpe: "7-8",
          rest: 70,
          restLabel: "70 sec",
          weightMode: "free",
          image: "bb-back-squat.png",
          video: "https://www.youtube.com/watch?v=ultWZbUMPL8",
          tip: "Primary lower body strength marker. Full depth (hip crease at or below knee level). Brace hard before each rep. Controlled descent, powerful drive out of the hole. Feet roughly shoulder width, toes pointed slightly out.",
          isFinisher: false
        },
        {
          id: "romanian-deadlift",
          name: "Romanian Deadlift",
          tier: 1,
          sets: 4,
          reps: "5",
          rpe: "7-8",
          rest: 70,
          restLabel: "70 sec",
          weightMode: "free",
          image: "romanian-deadlift.png",
          video: "https://www.youtube.com/watch?v=7j-2w4-P14I",
          tip: "Bar stays close to the legs. Push the hips back until you feel a strong stretch in the hamstrings, then drive the hips forward to stand. This is a hinge, not a squat. Slight knee bend that doesn't change throughout the rep.",
          isFinisher: false
        },
        {
          id: "leg-press",
          name: "Leg Press",
          tier: 2,
          sets: 3,
          reps: "8",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "leg-press.png",
          video: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
          tip: "Feet high and wide for more glute and hamstring emphasis, or centered for quad emphasis. Full range of motion, knees tracking over toes. Don't lock out at the top.",
          isFinisher: false
        },
        {
          id: "standing-calf-raise",
          name: "Weighted Standing Calf Raises",
          tier: 1,
          sets: 4,
          reps: "10",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "standing-calf-raise.png",
          video: "https://www.youtube.com/watch?v=YMVhHmKSsqI",
          tip: "Load this heavy. Full stretch at the bottom (let the heels drop), hard squeeze at the top with a two-count hold. Calves respond to heavy loads and full range. Don't bounce.",
          isFinisher: false
        },
        {
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "hanging-leg-raise.png",
          video: "https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form",
          tip: "Start with knees tucked if straight legs make you swing. The goal is curling the pelvis up at the top, not just lifting the legs. No swinging. If you are using momentum, drop to bent knees and rebuild it.",
          isFinisher: false
        },
        {
          id: "farmer-carry",
          name: "Farmer Carry",
          sets: 3,
          reps: "40 yd",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 3,
          image: "farmer-carry.png",
          video: "https://www.youtube.com/results?search_query=farmer+carry+proper+form",
          tip: "Log the weight in ONE hand. Heavy dumbbells or handles, ribs down, shoulders back, walk tall and controlled. Grip usually quits first, which is the training effect. Nothing after this needs your grip, so empty the tank.",
          isFinisher: false
        },
        {
          id: "cable-crunch",
          name: "Cable Crunch",
          sets: 3,
          reps: "15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "cable-crunch.png",
          video: "https://www.youtube.com/results?search_query=cable+crunch+proper+form+abs",
          tip: "Kneel facing the stack, rope beside the ears, hips locked in place. Curl the ribcage toward the pelvis. The hips must not move. If you are bowing at the hips it is a lat pulldown for your abs and does nothing.",
          isFinisher: false
        }
      ]
    },

    // =========================================================
    // PUSH B — HYPERTROPHY
    // =========================================================
    "push-b": {
      id: "push-b",
      name: "Push B",
      type: "hypertrophy",
      label: "Hypertrophy",
      goal: "Volume — moderate loads, higher reps, controlled tempos",
      estimatedMinutes: 58,
      minutesBySize: { light: 30, normal: 58, extended: 84 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Arm circles, 10 each direction",
          "Band dislocates (pass band over and behind head), 10 slow reps",
          "Scapular push-ups (protract and retract shoulder blades without bending elbows), 10 reps",
          "Light cable flyes, 12 reps to get blood into the chest"
        ]
      },
      exercises: [
        {
          id: "pike-pushup",
          name: "Pike Push-Ups",
          tier: 2,
          sets: 2,
          reps: "to failure",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          image: "pike-pushup.png",
          video: "https://www.youtube.com/watch?v=sposDXWEB0A",
          tip: "Hips high, head between the arms, pressing vertically. Entry point toward handstand push-ups. If too hard, elevate feet on a bench to reduce load. Track rep counts. When hitting 15+ on both sets, elevate feet higher.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Building toward handstand push-ups. Pike push-ups build overhead pressing strength and shoulder stability."
        },
        {
          id: "db-incline-press",
          name: "Dumbbell Incline Press",
          tier: 1,
          sets: 4,
          reps: "10-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "db-incline-press.png",
          video: "https://www.youtube.com/watch?v=8iPEnn-ltC8",
          tip: "Set bench to 30-degree incline. Three-count descent on every rep. Squeeze at the top without clanking the dumbbells together. Shifts emphasis to upper chest and front delts.",
          isFinisher: false
        },
        {
          id: "cable-flyes",
          name: "Cable Flyes",
          tier: 2,
          sets: 3,
          reps: "12-15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "cable-flyes.png",
          video: "https://www.youtube.com/watch?v=Iwe6AmxVf7o",
          tip: "Slight bend in the elbows, maintained throughout. Think hugging motion. Squeeze for a one-count at peak contraction. Light enough to feel the muscle, heavy enough that 15 is actually hard.",
          isFinisher: false
        },
        {
          id: "db-lateral-raise",
          name: "Dumbbell Lateral Raises",
          tier: 1,
          sets: 4,
          reps: "12-15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "db-lateral-raise.png",
          video: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
          tip: "Slight forward lean, thumbs tilted slightly down (like pouring water). Controlled up, slow down. Don't ego-lift these. Feel the burn at rep 10, fight for 15.",
          isFinisher: false
        },
        {
          id: "tricep-pushdown",
          name: "Tricep Pushdowns",
          tier: 2,
          sets: 3,
          reps: "12-15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "tricep-pushdown.png",
          video: "https://www.youtube.com/watch?v=2-LAMcpzODU",
          tip: "Elbows pinned to the sides. Full extension at the bottom, controlled return. Two different tricep angles in one session gives balanced development across all three heads.",
          isFinisher: false
        },
        {
          id: "cable-oh-tricep-ext",
          name: "Overhead Tricep Extension",
          tier: 3,
          sets: 3,
          reps: "12-15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "cable-oh-tricep-ext.png",
          video: "https://www.youtube.com/watch?v=kiuVA0gs3EI",
          tip: "Face away from cable stack, rope behind the head. Extend fully overhead, squeeze at lockout. The long head of the tricep gets stretched in this position, which is important since flat pressing doesn't load it well.",
          isFinisher: false
        },
        {
          id: "back-extension",
          name: "Back Extension",
          sets: 3,
          reps: "12-15",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "back-extension.png",
          video: "https://www.youtube.com/results?search_query=45+degree+back+extension+proper+form",
          tip: "Log 0 until bodyweight is easy for 3 sets of 15, then hold a plate to the chest. Hinge at the hips, not the spine. Rise until the body is a straight line and STOP. Hyperextending past that is how you turn a prehab exercise into the thing that hurt you.",
          isFinisher: false
        },
        {
          id: "crunch-machine",
          name: "Crunch Machine",
          sets: 3,
          reps: "15-20",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "crunch-machine.png",
          video: "https://www.youtube.com/results?search_query=ab+crunch+machine+proper+form",
          tip: "Set the seat so the pivot sits at your navel, not your chest. Short range, controlled, no yanking with the arms. Two-second squeeze at the bottom of the crunch.",
          isFinisher: false
        },
        {
          id: "supine-neck-flexion",
          name: "Supine Neck Flexion",
          sets: 3,
          reps: "12",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "supine-neck-flexion.png",
          video: "https://www.youtube.com/results?search_query=lying+weighted+neck+flexion+tutorial",
          tip: "Lie face-up with the head off the end of the bench. Log 0 and use bodyweight only for the first 3-4 weeks. Chin tucks toward the chest, slow down on the way back. When you add a plate, wrap it in a towel and start at 2.5 lbs. Any sharp pain or tingling, stop the set.",
          isFinisher: false
        }
      ]
    },

    // =========================================================
    // PULL B — HYPERTROPHY
    // =========================================================
    "pull-b": {
      id: "pull-b",
      name: "Pull B",
      type: "hypertrophy",
      label: "Hypertrophy",
      goal: "Volume — moderate loads, higher reps, controlled tempos",
      estimatedMinutes: 58,
      minutesBySize: { light: 30, normal: 58, extended: 84 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Band pull-aparts, 15 reps",
          "Arm circles, 10 each direction",
          "Scapular pull-ups (pull shoulder blades down without bending elbows), 8 reps",
          "Light single-arm dumbbell rows, 12 reps to activate the lats"
        ]
      },
      exercises: [
        {
          id: "inverted-row",
          name: "Inverted Rows",
          tier: 2,
          sets: 2,
          reps: "to failure",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          image: "inverted-row.png",
          video: "https://www.youtube.com/watch?v=dYNdjKjMbyc",
          tip: "Bar in rack at waist height. Hang underneath, body straight, pull chest to bar. More horizontal = harder. Start at an angle that allows 8+ reps. When horizontal at 15+, add a weighted vest or elevate feet.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Building toward advanced pull-up variations. Inverted rows build horizontal pulling endurance."
        },
        {
          id: "seated-cable-row",
          name: "Seated Cable Row",
          tier: 1,
          sets: 4,
          reps: "10-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "seated-cable-row.png",
          video: "https://www.youtube.com/watch?v=GZbfZ033f74",
          tip: "Sit upright, pull handle to lower chest, squeeze shoulder blades for a one-count. Three-count return on every rep. Pull with the elbows, not the hands.",
          isFinisher: false
        },
        {
          id: "wide-lat-pulldown",
          name: "Wide-Grip Lat Pulldown",
          tier: 1,
          sets: 4,
          reps: "10-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "wide-lat-pulldown.png",
          video: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
          tip: "Pull to upper chest, not behind neck. Lean back slightly. Drive elbows down toward hips. Slow negative on every rep. Complements heavy pull-ups on power day through different grip width and angle.",
          isFinisher: false
        },
        {
          id: "face-pulls",
          name: "Face Pulls",
          tier: 2,
          sets: 3,
          reps: "15",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "face-pulls.png",
          video: "https://www.youtube.com/watch?v=rep-qVOkqgk",
          tip: "Cable at face height. Pull toward face with elbows high, externally rotating so hands finish beside ears. Non-negotiable shoulder health work. Rear delts and rotator cuff muscles that keep shoulders functioning through all the pressing.",
          isFinisher: false
        },
        {
          id: "db-shrugs",
          name: "Dumbbell Shrugs",
          sets: 3,
          reps: "12-15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "db-shrugs.png",
          video: "https://www.youtube.com/results?search_query=dumbbell+shrug+proper+form+traps",
          tip: "Dumbbells at the sides means no bar blocking the bottom, so you get a real stretch before the shrug. Straight up, pause a beat at the top, lower slowly. No rolling the shoulders, which does nothing but grind the joint.",
          isFinisher: false
        },
        {
          id: "db-hammer-curls",
          name: "Dumbbell Hammer Curls",
          tier: 2,
          sets: 3,
          reps: "12",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "db-hammer-curls.png",
          video: "https://www.youtube.com/watch?v=zC3nLlEvin4",
          tip: "Neutral grip (palms facing each other). Alternating or simultaneous. Controlled, no swinging. Hits brachialis and brachioradialis for arm thickness and forearm development.",
          isFinisher: false
        },
        {
          id: "rear-delt-flyes",
          name: "Rear Delt Flyes",
          tier: 3,
          sets: 3,
          reps: "12-15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "rear-delt-flyes.png",
          video: "https://www.youtube.com/watch?v=EA7u4Q_8HQ0",
          tip: "Bent over, slight elbow bend, raise out to sides with a squeeze at top. Light weight, high control. Balances all the pressing in this program.",
          isFinisher: false
        },
        {
          id: "back-extension",
          name: "Back Extension",
          sets: 3,
          reps: "12-15",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "back-extension.png",
          video: "https://www.youtube.com/results?search_query=45+degree+back+extension+proper+form",
          tip: "Log 0 until bodyweight is easy for 3 sets of 15, then hold a plate to the chest. Hinge at the hips, not the spine. Rise until the body is a straight line and STOP. Hyperextending past that is how you turn a prehab exercise into the thing that hurt you.",
          isFinisher: false
        },
        {
          id: "prone-neck-extension",
          name: "Prone Neck Extension",
          sets: 3,
          reps: "12",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "prone-neck-extension.png",
          video: "https://www.youtube.com/results?search_query=prone+weighted+neck+extension+tutorial",
          tip: "Face-down, head off the bench. Bodyweight only to start, log 0. Look up slowly, lower slower. Pairs with supine flexion on the other push day so the neck gets balanced work front and back. Same rule: sharp pain means stop, not push through.",
          isFinisher: false
        }
      ]
    },

    // =========================================================
    // LEGS B — HYPERTROPHY
    // =========================================================
    "legs-b": {
      id: "legs-b",
      name: "Legs B",
      type: "hypertrophy",
      label: "Hypertrophy",
      goal: "Volume — moderate loads, higher reps, controlled tempos",
      estimatedMinutes: 62,
      minutesBySize: { light: 30, normal: 62, extended: 86 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Leg swings, 10 each direction per leg",
          "Hip circles, 8 each direction",
          "Bodyweight squats, 10 reps",
          "Glute bridges on the floor, 10 reps with squeeze at top",
          "Lateral band walks, 10 steps each direction (if band available)"
        ]
      },
      exercises: [
        {
          id: "assisted-pistol-squat",
          name: "Assisted Pistol Squats",
          tier: 2,
          sets: 2,
          reps: "max each leg",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          image: "assisted-pistol-squat.png",
          video: "https://www.youtube.com/watch?v=qDcniqddTeE",
          tip: "Hold a rack post or TRX for balance. Lower on one leg to bench, touch glutes to surface, stand up. Use as much assistance as needed. Progressively lower box height and reduce hold over weeks. When you can pistol to a standard bench unassisted for 5+ reps per leg, the box comes away.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Building toward full unassisted pistol squats. Assisted pistols build single-leg strength, balance, and ankle mobility."
        },
        {
          id: "bulgarian-split-squat",
          name: "Bulgarian Split Squats",
          tier: 1,
          sets: 4,
          reps: "10-12 each",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "bulgarian-split-squat.png",
          video: "https://www.youtube.com/watch?v=2C-uNgKwPLE",
          tip: "Rear foot on bench. Dumbbells at sides. Drop back knee straight down, drive through front heel. Unilateral work exposes and fixes imbalances bilateral squats hide. Rest between legs, not between sets.",
          isFinisher: false
        },
        {
          id: "lying-leg-curl",
          name: "Lying Leg Curl",
          tier: 1,
          sets: 4,
          reps: "12",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "lying-leg-curl.png",
          video: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
          tip: "Squeeze hard at peak contraction, three-count negative on every rep. Don't let hips lift off the pad. RDL on power day loads hamstrings stretched; leg curl loads them shortened. You need both.",
          isFinisher: false
        },
        {
          id: "leg-extension",
          name: "Leg Extension",
          tier: 2,
          sets: 4,
          reps: "12",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "leg-extension.png",
          video: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
          tip: "Full extension at top with one-count squeeze. Slow negative. Quads in isolation. Complements squat and split squat patterns.",
          isFinisher: false
        },
        {
          id: "hip-abduction",
          name: "Hip Abduction Machine",
          sets: 3,
          reps: "15-20",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 2,
          image: "hip-abduction.png",
          video: "https://www.youtube.com/results?search_query=hip+abduction+machine+glute+medius+form",
          tip: "Lean the torso slightly forward to bias the glute medius over the TFL. Push out under control, resist all the way back in. Weak abductors are a common source of knee and lower back complaints, so treat this as real work, not a cooldown.",
          isFinisher: false
        },
        {
          id: "walking-lunges",
          name: "Walking Lunges",
          tier: 3,
          sets: 3,
          reps: "12 each",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          image: "walking-lunges.png",
          video: "https://www.youtube.com/watch?v=L8fvypPrzzs",
          tip: "Dumbbells at sides. Long stride, upright torso, back knee kisses floor. High-fatigue by design after split squats, curls, and extensions. Moderate weight, quality steps.",
          isFinisher: false
        },
        {
          id: "seated-calf-raise",
          name: "Seated Calf Raises",
          tier: 2,
          sets: 4,
          reps: "15",
          rpe: "9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          image: "seated-calf-raise.png",
          video: "https://www.youtube.com/watch?v=JbyjNymZOt0",
          tip: "Full stretch at bottom, hard squeeze at top. Seated raises emphasize the soleus (deeper calf muscle underneath the gastrocnemius). Standing raises on power day hit the gastroc. Both days, both muscles.",
          isFinisher: false
        },
        {
          id: "suitcase-carry",
          name: "Suitcase Carry",
          sets: 3,
          reps: "40 yd ea",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 3,
          image: "suitcase-carry.png",
          video: "https://www.youtube.com/results?search_query=suitcase+carry+core+exercise+form",
          tip: "One weight, one side, walk without leaning. The obliques on the empty side are doing the work, fighting to keep you upright. This is direct anti-tilt training for the same lower back the back extensions are protecting. Switch hands each set.",
          isFinisher: false
        },
        {
          id: "back-extension",
          name: "Back Extension",
          sets: 3,
          reps: "12-15",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "back-extension.png",
          video: "https://www.youtube.com/results?search_query=45+degree+back+extension+proper+form",
          tip: "Log 0 until bodyweight is easy for 3 sets of 15, then hold a plate to the chest. Hinge at the hips, not the spine. Rise until the body is a straight line and STOP. Hyperextending past that is how you turn a prehab exercise into the thing that hurt you.",
          isFinisher: false
        }
      ]
    }
  ,

    // =========================================================
    // ALTERNATES — swap in from the workout picker
    // =========================================================
    "cal-push": {
      id: "cal-push",
      name: "Calisthenics Push",
      type: "calisthenics",
      label: "Bodyweight",
      code: "CP",
      goal: "Pushing volume with no equipment beyond the floor and a bench or bar",
      estimatedMinutes: 55,
      minutesBySize: { light: 28, normal: 55, extended: 78 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Arm circles, 10 forward and 10 back",
          "Scapular push-ups, 12 reps from a plank",
          "Wrist circles and wrist rocks, 30 seconds",
          "Slow push-ups, 8 reps at half effort"
        ]
      },
      exercises: [
        {
          id: "pike-pushup",
          name: "Pike Push-Ups",
          sets: 3,
          reps: "8-15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "pike-pushup.png",
          video: "https://www.youtube.com/results?search_query=pike+push+up+handstand+progression",
          tip: "Hips high, head between the hands, press the floor away. The closer the feet come to the hands, the more vertical the press and the closer to a handstand push-up.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Primer for the handstand push-up. Fresh legs on this, not leftovers."
        },
        {
          id: "pushup",
          name: "Push-Ups",
          sets: 4,
          reps: "12-20",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "pushup.png",
          video: "https://www.youtube.com/results?search_query=push+up+proper+form",
          tip: "Hands under the shoulders, body in one line from heel to head. Elbows about 45 degrees from the ribs, not flared to 90. Too easy? Elevate the feet. Too hard? Hands on a bench.",
          isFinisher: false
        },
        {
          id: "bench-dip",
          name: "Bench or Bar Dips",
          sets: 3,
          reps: "10-15",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "bench-dip.png",
          video: "https://www.youtube.com/results?search_query=parallel+bar+dips+form",
          tip: "Parallel bars if the park has them, a bench edge if not. Lean forward slightly for more chest, stay upright for more triceps. Stop when the upper arms hit parallel, going deeper wrecks shoulders.",
          isFinisher: false
        },
        {
          id: "diamond-pushup",
          name: "Diamond Push-Ups",
          sets: 3,
          reps: "8-15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "diamond-pushup.png",
          video: "https://www.youtube.com/results?search_query=diamond+push+up+form",
          tip: "Index fingers and thumbs touching under the sternum. This is your triceps work without a cable stack. Keep the elbows tucked tight to the body the whole way down.",
          isFinisher: false
        },
        {
          id: "archer-pushup",
          name: "Archer Push-Ups",
          sets: 3,
          reps: "5-8 ea",
          rpe: "9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 3,
          image: "archer-pushup.png",
          video: "https://www.youtube.com/results?search_query=archer+push+up+tutorial",
          tip: "Wide hands, shift onto one side as you lower, the other arm stays straight. The bridge to one-arm push-ups. Go slow, the straight arm wants to collapse.",
          isFinisher: false
        },
        {
          id: "superman",
          name: "Superman Hold",
          sets: 3,
          reps: "30s",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "superman.png",
          video: "https://www.youtube.com/results?search_query=superman+exercise+lower+back",
          tip: "Face down, lift chest and thighs off the floor together. This is the back extension substitute when there is no bench. Squeeze the glutes, do not crank the neck up, keep the gaze at the floor.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "hollow-hold",
          name: "Hollow Body Hold",
          sets: 3,
          reps: "20-40s",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "hollow-hold.png",
          video: "https://www.youtube.com/results?search_query=hollow+body+hold+tutorial",
          tip: "Lower back pressed flat into the floor, shoulders and legs raised. If the back arches, raise the legs higher until it does not. The hardest easy exercise in gymnastics.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head moving. Hold 10 seconds. Repeat on the back and each side. No load, no motion, no momentum.",
          isFinisher: false
        }
      ]
    },

    "cal-pull": {
      id: "cal-pull",
      name: "Calisthenics Pull",
      type: "calisthenics",
      label: "Bodyweight",
      code: "CB",
      goal: "Pulling volume from a bar. Park pull-up bar or anything you can hang from",
      estimatedMinutes: 55,
      minutesBySize: { light: 28, normal: 55, extended: 78 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Arm circles, 10 each direction",
          "Scapular pulls from a dead hang, 8 reps",
          "Band pull-aparts or arm swings, 15 reps",
          "Two easy sets of 3 pull-ups at half effort"
        ]
      },
      exercises: [
        {
          id: "pullup-bw",
          name: "Pull-Ups",
          sets: 4,
          reps: "5-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 1,
          image: "pullup-bw.png",
          video: "https://www.youtube.com/results?search_query=strict+pull+up+form",
          tip: "Bodyweight version. Full hang at the bottom, chin clears the bar at the top, no kipping. Can't get the reps? Jump to the top and lower yourself as slowly as possible, which builds the strength faster than band assistance.",
          isFinisher: false
        },
        {
          id: "inverted-row",
          name: "Inverted Rows",
          sets: 3,
          reps: "10-15",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "inverted-row.png",
          video: "https://www.youtube.com/results?search_query=inverted+row+bodyweight+form",
          tip: "Bar at hip height, body straight, pull the chest to the bar. Lower the bar to make it harder, raise it to make it easier. Horizontal pulling, which balances all the pushing.",
          isFinisher: false
        },
        {
          id: "chinup-bw",
          name: "Chin-Ups",
          sets: 3,
          reps: "6-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 2,
          image: "chinup-bw.png",
          video: "https://www.youtube.com/results?search_query=chin+up+proper+form",
          tip: "Palms toward you, hands shoulder width. More biceps than a pull-up, which is the point on a day with no curls available.",
          isFinisher: false
        },
        {
          id: "superman",
          name: "Superman Hold",
          sets: 3,
          reps: "30s",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "superman.png",
          video: "https://www.youtube.com/results?search_query=superman+exercise+lower+back",
          tip: "Face down, lift chest and thighs off the floor together. This is the back extension substitute when there is no bench. Squeeze the glutes, do not crank the neck up, keep the gaze at the floor.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "hanging-leg-raise.png",
          video: "https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form",
          tip: "Start with knees tucked if straight legs make you swing. The goal is curling the pelvis up at the top, not just lifting the legs. No swinging.",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head moving. Hold 10 seconds. Repeat on the back and each side. No load, no motion, no momentum.",
          isFinisher: false
        },
        {
          id: "hollow-hold",
          name: "Hollow Body Hold",
          sets: 3,
          reps: "20-40s",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "hollow-hold.png",
          video: "https://www.youtube.com/results?search_query=hollow+body+hold+tutorial",
          tip: "Lower back pressed flat into the floor, shoulders and legs raised. If the back arches, raise the legs higher until it does not. The hardest easy exercise in gymnastics.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "dead-hang",
          name: "Dead Hangs",
          sets: 2,
          reps: "max time",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "dead-hang.png",
          video: "https://www.youtube.com/results?search_query=dead+hang+grip+strength",
          tip: "Full grip, shoulders engaged rather than shrugged to the ears. Track the times. Over 60 seconds consistently, start adding scapular pulls from the hang.",
          trackMode: "time",
          isFinisher: true,
          finisherProgression: "Grip endurance for every pulling movement you own. Always last, never before the rows."
        }
      ]
    },

    "cal-legs": {
      id: "cal-legs",
      name: "Calisthenics Legs",
      type: "calisthenics",
      label: "Bodyweight",
      code: "CL",
      goal: "Leg volume through tempo, single-leg work, and reps instead of load",
      estimatedMinutes: 55,
      minutesBySize: { light: 28, normal: 55, extended: 78 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Leg swings, 10 each direction per leg",
          "Bodyweight squats, 15 easy reps",
          "Walking knee hugs and ankle rolls, 30 seconds",
          "Glute bridges, 15 reps"
        ]
      },
      exercises: [
        {
          id: "broad-jump",
          name: "Broad Jumps",
          sets: 3,
          reps: "5",
          rpe: "-",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 2,
          image: "broad-jump.png",
          video: "https://www.youtube.com/results?search_query=broad+jump+technique",
          tip: "Swing the arms, jump forward for distance, land soft with bent knees. Replaces box jumps: same hip power, nothing to trip over. Reset fully between reps, this is a power exercise not conditioning.",
          isFinisher: false,
          isPrimer: true,
          finisherProgression: "Hip power without a box to catch your shin. Fresh, before the legs are cooked."
        },
        {
          id: "bw-squat",
          name: "Bodyweight Squats",
          sets: 4,
          reps: "20-30",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "bw-squat.png",
          video: "https://www.youtube.com/results?search_query=bodyweight+squat+form",
          tip: "Feet shoulder width, sit back and down, knees tracking over the toes. If 30 is easy, slow the descent to a five count. Tempo turns an easy movement into real work without adding load.",
          isFinisher: false
        },
        {
          id: "single-leg-rdl",
          name: "Single-Leg RDL",
          sets: 3,
          reps: "10-12 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "single-leg-rdl.png",
          video: "https://www.youtube.com/results?search_query=single+leg+romanian+deadlift+bodyweight",
          tip: "Hinge at the hip, back leg extends behind as a counterweight, spine stays long. Balance is part of the exercise. This is your hamstring and lower back work when there is no barbell.",
          isFinisher: false
        },
        {
          id: "bw-lunge",
          name: "Walking Lunges",
          sets: 3,
          reps: "16-20 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "bw-lunge.png",
          video: "https://www.youtube.com/results?search_query=bodyweight+walking+lunge+form",
          tip: "Long step, back knee toward the floor, front shin close to vertical. Bodyweight version, so chase reps and control rather than load.",
          isFinisher: false
        },
        {
          id: "step-up",
          name: "Step-Ups",
          sets: 3,
          reps: "12-15 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "step-up.png",
          video: "https://www.youtube.com/results?search_query=step+up+exercise+form",
          tip: "Bench, box, or a park wall about knee height. Drive through the heel of the top foot, do not push off the trailing leg. Control the way down.",
          isFinisher: false
        },
        {
          id: "glute-bridge",
          name: "Single-Leg Glute Bridge",
          sets: 3,
          reps: "12-15 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "glute-bridge.png",
          video: "https://www.youtube.com/results?search_query=single+leg+glute+bridge+form",
          tip: "One foot planted, other leg extended. Drive through the heel, squeeze at the top for a beat, lower under control. Ribs down so the lower back does not take over the movement.",
          isFinisher: false
        },
        {
          id: "bw-calf-raise",
          name: "Single-Leg Calf Raise",
          sets: 3,
          reps: "15-20 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "bw-calf-raise.png",
          video: "https://www.youtube.com/results?search_query=single+leg+calf+raise+form",
          tip: "One leg, off a step or curb if you have one, full stretch at the bottom and a hard squeeze at the top. Bodyweight on one leg is roughly what two legs loaded would give you.",
          isFinisher: false
        },
        {
          id: "wall-sit",
          name: "Wall Sit",
          sets: 3,
          reps: "max time",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "wall-sit.png",
          video: "https://www.youtube.com/results?search_query=wall+sit+proper+form",
          tip: "Back flat to the wall, thighs parallel to the floor, no hands on the knees. Track the time. Pure quad endurance, and it burns in a way that squats do not.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "assisted-pistol-squat",
          name: "Assisted Pistol Squats",
          sets: 2,
          reps: "max ea",
          rpe: "-",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "assisted-pistol-squat.png",
          video: "https://www.youtube.com/results?search_query=pistol+squat+progression+tutorial",
          tip: "Hold a post or doorframe for balance, one leg forward, sit all the way down. Use as little assistance as you can manage. Building to the unassisted pistol.",
          isFinisher: false
        }
      ]
    },

    "cal-full": {
      id: "cal-full",
      name: "Calisthenics Full Body",
      type: "calisthenics",
      label: "Bodyweight",
      code: "CF",
      goal: "One session that touches everything. The travel and no-gym default",
      estimatedMinutes: 58,
      minutesBySize: { light: 30, normal: 58, extended: 82 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Arm circles and leg swings, 30 seconds each",
          "Bodyweight squats, 15 reps",
          "Scapular push-ups, 10 reps",
          "Glute bridges, 15 reps"
        ]
      },
      exercises: [
        {
          id: "pushup",
          name: "Push-Ups",
          sets: 4,
          reps: "12-20",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "pushup.png",
          video: "https://www.youtube.com/results?search_query=push+up+proper+form",
          tip: "Hands under the shoulders, body in one line from heel to head. Elbows about 45 degrees from the ribs, not flared to 90. Too easy? Elevate the feet. Too hard? Hands on a bench.",
          isFinisher: false
        },
        {
          id: "pullup-bw",
          name: "Pull-Ups",
          sets: 4,
          reps: "5-12",
          rpe: "8-9",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 1,
          image: "pullup-bw.png",
          video: "https://www.youtube.com/results?search_query=strict+pull+up+form",
          tip: "Bodyweight version. Full hang at the bottom, chin clears the bar at the top, no kipping. Can't get the reps? Jump to the top and lower yourself as slowly as possible, which builds the strength faster than band assistance.",
          isFinisher: false
        },
        {
          id: "bw-squat",
          name: "Bodyweight Squats",
          sets: 4,
          reps: "20-30",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "bw-squat.png",
          video: "https://www.youtube.com/results?search_query=bodyweight+squat+form",
          tip: "Feet shoulder width, sit back and down, knees tracking over the toes. If 30 is easy, slow the descent to a five count. Tempo turns an easy movement into real work without adding load.",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head moving. Hold 10 seconds. Repeat on the back and each side. No load, no motion, no momentum.",
          isFinisher: false
        },
        {
          id: "inverted-row",
          name: "Inverted Rows",
          sets: 3,
          reps: "10-15",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "inverted-row.png",
          video: "https://www.youtube.com/results?search_query=inverted+row+bodyweight+form",
          tip: "Bar at hip height, body straight, pull the chest to the bar. Lower the bar to make it harder, raise it to make it easier. Horizontal pulling, which balances all the pushing.",
          isFinisher: false
        },
        {
          id: "single-leg-rdl",
          name: "Single-Leg RDL",
          sets: 3,
          reps: "10-12 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "single-leg-rdl.png",
          video: "https://www.youtube.com/results?search_query=single+leg+romanian+deadlift+bodyweight",
          tip: "Hinge at the hip, back leg extends behind as a counterweight, spine stays long. Balance is part of the exercise. This is your hamstring and lower back work when there is no barbell.",
          isFinisher: false
        },
        {
          id: "superman",
          name: "Superman Hold",
          sets: 3,
          reps: "30s",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "superman.png",
          video: "https://www.youtube.com/results?search_query=superman+exercise+lower+back",
          tip: "Face down, lift chest and thighs off the floor together. This is the back extension substitute when there is no bench. Squeeze the glutes, do not crank the neck up, keep the gaze at the floor.",
          trackMode: "time",
          isFinisher: false
        },
        {
          id: "pike-pushup",
          name: "Pike Push-Ups",
          sets: 3,
          reps: "8-15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "pike-pushup.png",
          video: "https://www.youtube.com/results?search_query=pike+push+up+handstand+progression",
          tip: "Hips high, head between the hands, press the floor away. The closer the feet come to the hands, the more vertical the press and the closer to a handstand push-up.",
          isFinisher: false
        },
        {
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "hanging-leg-raise.png",
          video: "https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form",
          tip: "Start with knees tucked if straight legs make you swing. The goal is curling the pelvis up at the top, not just lifting the legs. No swinging.",
          isFinisher: false
        },
        {
          id: "burpee",
          name: "Burpees",
          sets: 3,
          reps: "10-15",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "bw",
          tier: 3,
          image: "burpee.png",
          video: "https://www.youtube.com/results?search_query=burpee+proper+form",
          tip: "Chest to the floor, full stand at the top. Pace yourself, this is the conditioning piece. Skip the jump if the knees complain.",
          isFinisher: false
        }
      ]
    },

    "back-core": {
      id: "back-core",
      name: "Back & Core",
      type: "power",
      label: "Posterior & Core",
      code: "C",
      goal: "Everything protecting the lower back and neck, in one session",
      estimatedMinutes: 55,
      minutesBySize: { light: 30, normal: 55, extended: 78 },
      warmup: {
        name: "Dynamic Warm-Up",
        duration: "5 minutes",
        movements: [
          "Cat-cow, 10 slow reps",
          "Bird dog, 8 reps each side",
          "Band pull-aparts, 15 reps",
          "Glute bridges, 15 reps"
        ]
      },
      exercises: [
        {
          id: "back-extension",
          name: "Back Extension",
          sets: 3,
          reps: "12-15",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 1,
          image: "back-extension.png",
          video: "https://www.youtube.com/results?search_query=45+degree+back+extension+proper+form",
          tip: "Log 0 until bodyweight is easy for 3 sets of 15, then hold a plate. Hinge at the hips, not the spine. Rise until the body is a straight line and STOP.",
          isFinisher: false
        },
        {
          id: "chest-supported-row",
          name: "Chest-Supported Row",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 1,
          image: "chest-supported-row.png",
          video: "https://www.youtube.com/results?search_query=chest+supported+row+form",
          tip: "Chest pinned to the pad, which takes the lower back out entirely. Pull to the lower ribs, squeeze, control back.",
          isFinisher: false
        },
        {
          id: "dead-bug",
          name: "Dead Bug",
          sets: 3,
          reps: "10-12 ea",
          rpe: "7-8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 1,
          image: "dead-bug.png",
          video: "https://www.youtube.com/results?search_query=dead+bug+exercise+form",
          tip: "On your back, opposite arm and leg extend while the lower back stays glued to the floor. Slow. If the back lifts, shorten the range. Teaches the bracing that protects your spine under load.",
          isFinisher: false
        },
        {
          id: "neck-isometrics",
          name: "Neck Isometrics",
          sets: 2,
          reps: "4 dir x 10s",
          rpe: "-",
          rest: 30,
          restLabel: "30 sec",
          weightMode: "bw",
          tier: 1,
          image: "neck-isometrics.png",
          video: "https://www.youtube.com/results?search_query=neck+isometric+exercises+for+neck+pain",
          tip: "Palm on the forehead, push the head into it without the head moving. Hold 10 seconds. Repeat on the back and each side. No load, no motion, no momentum.",
          isFinisher: false
        },
        {
          id: "face-pulls",
          name: "Face Pulls",
          sets: 3,
          reps: "15",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 2,
          image: "face-pulls.png",
          video: "https://www.youtube.com/results?search_query=face+pull+proper+form",
          tip: "Rope to the face, elbows high, externally rotate at the end so the knuckles finish pointing behind you. Shoulder health work disguised as a rear delt exercise.",
          isFinisher: false
        },
        {
          id: "pallof-press",
          name: "Pallof Press",
          sets: 3,
          reps: "12-15 ea",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 2,
          image: "pallof-press.png",
          video: "https://www.youtube.com/results?search_query=pallof+press+form",
          tip: "Cable or band at chest height, stand side-on, press straight out and resist the rotation. Nothing moves except your arms. This is anti-rotation work, which is the half of core training almost everyone skips.",
          isFinisher: false
        },
        {
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          sets: 3,
          reps: "10-12",
          rpe: "8",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 2,
          image: "hanging-leg-raise.png",
          video: "https://www.youtube.com/results?search_query=hanging+leg+raise+proper+form",
          tip: "Start with knees tucked if straight legs make you swing. The goal is curling the pelvis up at the top, not just lifting the legs. No swinging.",
          isFinisher: false
        },
        {
          id: "bird-dog",
          name: "Bird Dog",
          sets: 3,
          reps: "10-12 ea",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "bw",
          tier: 3,
          image: "bird-dog.png",
          video: "https://www.youtube.com/results?search_query=bird+dog+exercise+form",
          tip: "Hands and knees, opposite arm and leg extend to a straight line and hold two seconds. Hips stay square to the floor. Direct spinal stabilizer work, which is why it pairs with the back extensions.",
          isFinisher: false
        },
        {
          id: "cable-crunch",
          name: "Cable Crunch",
          sets: 3,
          reps: "15",
          rpe: "8-9",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "cable-crunch.png",
          video: "https://www.youtube.com/results?search_query=cable+crunch+proper+form+abs",
          tip: "Kneel facing the stack, rope beside the ears, hips locked. Curl the ribcage toward the pelvis. The hips must not move.",
          isFinisher: false
        },
        {
          id: "suitcase-carry",
          name: "Suitcase Carry",
          sets: 3,
          reps: "40 yd ea",
          rpe: "8",
          rest: 60,
          restLabel: "60 sec",
          weightMode: "free",
          tier: 3,
          image: "suitcase-carry.png",
          video: "https://www.youtube.com/results?search_query=suitcase+carry+core+exercise+form",
          tip: "One weight, one side, walk without leaning. The obliques on the empty side fight to keep you upright. Switch hands each set.",
          isFinisher: false
        },
        {
          id: "prone-neck-extension",
          name: "Prone Neck Extension",
          sets: 3,
          reps: "12",
          rpe: "7",
          rest: 45,
          restLabel: "45 sec",
          weightMode: "free",
          tier: 3,
          image: "prone-neck-extension.png",
          video: "https://www.youtube.com/results?search_query=prone+weighted+neck+extension+tutorial",
          tip: "Face-down, head off the bench. Bodyweight only to start, log 0. Look up slowly, lower slower. Sharp pain means stop, not push through.",
          isFinisher: false
        }
      ]
    }
},

  // e1RM calculation using Epley formula
  // weight × (1 + reps / 30)
  calculateE1RM: function(weight, reps) {
    if (reps === 1) return weight;
    return Math.round(weight * (1 + reps / 30));
  }
};

// Make available globally
if (typeof window !== 'undefined') {
  window.FORGE_DATA = FORGE_DATA;
}
