/* FORGE exercise figures: drawing engine and runtime. Generated by build.py. */
(function () {
"use strict";
/* =========================================================
   Vector helpers
   ========================================================= */
const D2R = Math.PI / 180;
const add = (a, b) => [a[0] + b[0], a[1] + b[1]];
const sub = (a, b) => [a[0] - b[0], a[1] - b[1]];
const mul = (a, s) => [a[0] * s, a[1] * s];
const dot = (a, b) => a[0] * b[0] + a[1] * b[1];
const len = a => Math.hypot(a[0], a[1]);
const nrm = a => { const l = len(a) || 1; return [a[0] / l, a[1] / l]; };
const lerp = (a, b, t) => a + (b - a) * t;
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
// angle in degrees: 0 = up, 90 = forward (right), 180 = down
const dir = deg => [Math.sin(deg * D2R), -Math.cos(deg * D2R)];
const rot = (v, th) => [v[0] * Math.cos(th) - v[1] * Math.sin(th), v[0] * Math.sin(th) + v[1] * Math.cos(th)];
const r1 = n => Math.round(n * 100) / 100;
const P = p => r1(p[0]) + " " + r1(p[1]);
const cross = (a, b) => a[0] * b[1] - a[1] * b[0];

const EASE = {
  lin: t => t,
  inOut: t => 0.5 - 0.5 * Math.cos(Math.PI * t),
  out: t => 1 - Math.pow(1 - t, 2.2),
  in: t => Math.pow(t, 1.8),
};

function lerpObj(a, b, t) {
  if (typeof a === "number") return lerp(a, b, t);
  if (Array.isArray(a)) return a.map((v, i) => lerpObj(v, b[i], t));
  if (a && typeof a === "object") { const o = {}; for (const k in a) o[k] = (k in b) ? lerpObj(a[k], b[k], t) : a[k]; return o; }
  return a;
}

/* =========================================================
   Shape primitives (all return SVG path data)
   ========================================================= */
function circle(c, r) {
  return `M${r1(c[0] - r)} ${r1(c[1])}a${r1(r)} ${r1(r)} 0 1 0 ${r1(2 * r)} 0a${r1(r)} ${r1(r)} 0 1 0 ${r1(-2 * r)} 0Z`;
}
// tapered capsule between A (radius ra) and B (radius rb), one clean outline
function capsule(A, B, ra, rb) {
  const v = sub(B, A), d = len(v);
  if (d < 0.05) return circle(A, Math.max(ra, rb));
  const u = mul(v, 1 / d), n = [-u[1], u[0]];
  const s = clamp((ra - rb) / d, -0.95, 0.95), c = Math.sqrt(1 - s * s);
  const m1 = add(mul(n, c), mul(u, s)), m2 = add(mul(n, -c), mul(u, s));
  const a1 = add(A, mul(m1, ra)), b1 = add(B, mul(m1, rb)), b2 = add(B, mul(m2, rb)), a2 = add(A, mul(m2, ra));
  const swB = cross(m1, u) > 0 ? 1 : 0, swA = cross(m2, mul(u, -1)) > 0 ? 1 : 0;
  const lgB = s < 0 ? 1 : 0, lgA = s >= 0 ? 1 : 0;
  return `M${P(a1)}L${P(b1)}A${r1(rb)} ${r1(rb)} 0 ${lgB} ${swB} ${P(b2)}L${P(a2)}A${r1(ra)} ${r1(ra)} 0 ${lgA} ${swA} ${P(a1)}Z`;
}
// smooth closed curve through points (Catmull-Rom)
function blob(pts) {
  const n = pts.length; let d = `M${P(pts[0])}`;
  for (let i = 0; i < n; i++) {
    const p0 = pts[(i - 1 + n) % n], p1 = pts[i], p2 = pts[(i + 1) % n], p3 = pts[(i + 2) % n];
    d += `C${P(add(p1, mul(sub(p2, p0), 1 / 6)))} ${P(sub(p2, mul(sub(p3, p1), 1 / 6)))} ${P(p2)}`;
  }
  return d + "Z";
}
function poly(pts) { return "M" + pts.map(P).join("L") + "Z"; }
function line(a, b) { return `M${P(a)}L${P(b)}`; }
// muscle belly lying along a limb segment. side: +1 / -1 picks a flank, 0 centres it
function spindle(A, B, ra, rb, t0, t1, side, thick = 1, reach = 0.42) {
  const u = nrm(sub(B, A)), n = [u[1], -u[0]], L = len(sub(B, A));
  const outer = [], inner = [], N = 10;
  for (let i = 0; i <= N; i++) {
    const s = i / N, t = lerp(t0, t1, s), r = lerp(ra, rb, t);
    const c = add(A, mul(u, L * t)), w = Math.pow(Math.sin(Math.PI * s), 0.7);
    const mid = side * r * reach, h = (side === 0 ? r * 0.72 : r * 0.44) * w * thick;
    outer.push(add(c, mul(n, mid + h))); inner.push(add(c, mul(n, mid - h)));
  }
  return "M" + outer.map(P).join("L") + "L" + inner.reverse().map(P).join("L") + "Z";
}
// a frame on a body part: points given as [along, across] mapped into world space
const frameOf = (origin, ax, ay) => ([a, x]) => add(origin, add(mul(ax, a), mul(ay, x)));

/* =========================================================
   Body model. Units: roughly centimetres, standing height ~175.
   ========================================================= */
const B = { trunk: 55, sh: 51.5, neck: 54, headUp: 15, ua: 31, fa: 26, grip: 33, thigh: 42.5, shin: 42 };

// side-view torso profile: [along 0..1 of trunk, across (+ = front)]
const TORSO_SIDE = [[-0.13,-5],[-0.1,-11],[0.02,-13],[0.18,-11.4],[0.34,-9.8],[0.55,-11.4],[0.78,-12.4],[0.93,-10.4],[1.02,-5],[1.03,2],[0.97,8],[0.86,11.4],[0.72,12.4],[0.6,10.4],[0.42,9.6],[0.22,10.2],[0.06,10.6],[-0.08,6],[-0.13,1]];
const SHORTS_SIDE = [[-0.145,-5.4],[-0.11,-11.8],[0.02,-13.8],[0.19,-12.2],[0.25,-11.2],[0.27,10.7],[0.2,11],[0.06,11.4],[-0.09,6.6],[-0.145,1]];
const MUS_SIDE = {
  lats:     [[0.36,-9.2],[0.55,-11],[0.74,-11.6],[0.8,-9],[0.66,-6.6],[0.48,-6.4]],
  midback:  [[0.66,-11.4],[0.84,-11.8],[0.92,-9.4],[0.84,-7.8],[0.72,-8.6]],
  traps:    [[0.86,-10.6],[0.96,-9.6],[1.01,-5.4],[0.95,-4.6],[0.88,-7.2]],
  erectors: [[0.06,-11],[0.3,-9.1],[0.46,-9.3],[0.4,-7],[0.2,-7.4],[0.06,-8.8]],
  glutes:   [[-0.1,-10.6],[0.02,-12.8],[0.16,-11.4],[0.13,-6.6],[0.0,-5.6],[-0.08,-6.6]],
  core:     [[0.18,7.2],[0.3,9],[0.5,9.2],[0.62,8.2],[0.5,4.2],[0.3,3.6]],
  chest:    [[0.7,9.8],[0.82,11.8],[0.93,9.6],[0.95,5.6],[0.84,4.4],[0.74,6]],
};
const HEAD = [[-10,-1.5],[-7.6,-8],[-1,-11],[5.4,-9.2],[9,-4.4],[9.4,-1.4],[11.6,1.8],[9.7,3.3],[9.9,5],[8.8,8.3],[4,10.2],[-2,8],[-7,5.4]];

/* Solve a side-view pose into world-space joints.
   pose: trunk, head, thighN/F, shinN/F, footN/F, uaN/F + faN/F (or hand targets), anchor [x,y]
   anchorJoint: which joint the anchor pins (ankleN, hip, shoulder) */
function solveSide(pose, anchorJoint, hands) {
  const J = {};
  const d = dir(pose.trunk), ant = [-d[1], d[0]];
  J.hip = [0, 0];
  J.shoulder = add(mul(d, B.sh), mul(ant, 1));
  J.neck = add(mul(d, B.neck), mul(ant, -1.5));
  J.headA = pose.head != null ? pose.head : pose.trunk * 0.4;
  J.head = add(J.neck, mul(dir(J.headA), B.headUp));
  for (const s of ["N", "F"]) {
    J["knee" + s] = mul(dir(pose["thigh" + s]), B.thigh);
    J["ankle" + s] = add(J["knee" + s], mul(dir(pose["shin" + s]), B.shin));
  }
  const off = sub(pose.anchor, J[anchorJoint]);
  for (const k of ["hip", "shoulder", "neck", "head", "kneeN", "kneeF", "ankleN", "ankleF"]) J[k] = add(J[k], off);
  J.d = d; J.ant = ant; J.pose = pose;
  J.T = frameOf(J.hip, mul(d, B.trunk), ant);
  // head frame: x forward along the face, y down
  const hf = dir(J.headA + 90), hd = mul(dir(J.headA), -1);
  J.H = ([x, y]) => add(J.head, add(mul(hf, x), mul(hd, y)));
  J.chin = J.H([8.8, 8.3]);
  // arms
  const tgt = hands ? hands(J) : null;
  for (const s of ["N", "F"]) {
    if (tgt && tgt[s]) {
      // wrist:true plants the wrist (hands flat on the floor); otherwise the grip closes on the target
      const { at, pref, wrist, handDir } = tgt[s];
      const L2 = wrist ? B.fa : B.grip;
      const S = J.shoulder, v = sub(at, S);
      const dd = clamp(len(v), Math.abs(B.ua - L2) + 0.5, B.ua + L2 - 0.3);
      const u = nrm(v), A = Math.acos(clamp((B.ua * B.ua + dd * dd - L2 * L2) / (2 * B.ua * dd), -1, 1));
      const e1 = add(S, mul(rot(u, A), B.ua)), e2 = add(S, mul(rot(u, -A), B.ua));
      const E = dot(sub(e1, S), pref) >= dot(sub(e2, S), pref) ? e1 : e2;
      const fu = nrm(sub(at, E));
      J["elbow" + s] = E; J["wrist" + s] = add(E, mul(fu, B.fa)); J["faDir" + s] = fu;
      if (wrist) { J["grip" + s] = add(J["wrist" + s], mul(handDir, 5)); J["handEnd" + s] = add(J["wrist" + s], mul(handDir, 9)); }
      else { J["grip" + s] = add(E, mul(fu, B.grip)); J["handEnd" + s] = add(J["grip" + s], mul(fu, 2)); }
    } else {
      J["elbow" + s] = add(J.shoulder, mul(dir(pose["ua" + s]), B.ua));
      const fu = dir(pose["fa" + s]);
      J["wrist" + s] = add(J["elbow" + s], mul(fu, B.fa)); J["grip" + s] = add(J["elbow" + s], mul(fu, B.grip)); J["faDir" + s] = fu;
      J["handEnd" + s] = add(J["grip" + s], mul(fu, 2));
    }
  }
  // feet
  for (const s of ["N", "F"]) {
    const u = dir(pose["foot" + s]), dn = [-u[1], u[0]], A = J["ankle" + s];
    J["heel" + s] = add(A, add(mul(u, -2.5), mul(dn, 4.2)));
    J["toe" + s] = add(A, add(mul(u, 14), mul(dn, 5.6)));
  }
  return J;
}
const soleY = (J, s) => Math.max(J["heel" + s][1] + 4.2, J["toe" + s][1] + 2.6);

/* ---------- shading, muscles, shorts ---------- */
// key light from upper front; each part is shaded across its own axis like a cylinder
const LIGHT = nrm([0.7, -0.72]);
const TONES = {
  body:   [["0", "#AEB4BC"], [".42", "#8C929B"], ["1", "#555A62"]],
  far:    [["0", "#62676F"], [".45", "#50555D"], ["1", "#363A40"]],
  shorts: [["0", "#454A51"], [".45", "#31353B"], ["1", "#1E2125"]],
  "shorts-far": [["0", "#2E3237"], [".5", "#25282D"], ["1", "#18191C"]],
};
function painter(mus, ghost) {
  const defs = [], out = [];
  let gi = 0;
  const gradAt = (tone, p1, p2) => {
    const id = `${mus.__id}g${gi++}`;
    defs.push({ tag: "linearGradient", a: { id, gradientUnits: "userSpaceOnUse", x1: r1(p1[0]), y1: r1(p1[1]), x2: r1(p2[0]), y2: r1(p2[1]) },
      kids: TONES[tone].map(([o, c]) => ({ tag: "stop", a: { offset: o, "stop-color": c } })) });
    return `fill:url(#${id})`;
  };
  // gradient across the A-B axis; fades to flat when the axis lines up with the light, so it never flips
  const across = (tone, A, B, r) => {
    const u = nrm(sub(B, A)), g = sub(LIGHT, mul(u, dot(LIGHT, u))), m = len(g);
    const gh = m > 1e-4 ? mul(g, 1 / m) : [0, -1], k = r / Math.max(m, 0.35), mid = mul(add(A, B), 0.5);
    return gradAt(tone, add(mid, mul(gh, k)), sub(mid, mul(gh, k)));
  };
  const radial = (tone, c, r) => gradAt(tone, add(c, mul(LIGHT, r)), sub(c, mul(LIGHT, r)));
  const part = (d, cls, style) => out.push({ tag: "path", a: { d, class: ghost ? "ghost" : cls, style: ghost ? "" : (style || "") } });
  // shaded part: tone doubles as the css class
  const shaded = (d, tone, A, B, r, extra = "") => part(d, tone + extra, ghost ? "" : across(tone, A, B, r));
  const muscle = (name, d) => {
    if (ghost || !mus[name]) return;
    const m = mus[name];
    part(d, "mus-halo", `opacity:${m.h}`);
    part(d, "mus", `opacity:${m.o}`);
  };
  return { defs, out, part, shaded, muscle, across, radial, gradAt };
}
// capsule cut straight across at fraction t from A: a shorts leg with a square hem
function capsuleCut(A, B, ra, rb, t) {
  const v = sub(B, A), d = len(v), u = mul(v, 1 / d), n = [-u[1], u[0]];
  const s = clamp((ra - rb) / d, -0.95, 0.95), c = Math.sqrt(1 - s * s);
  const m1 = add(mul(n, c), mul(u, s)), m2 = add(mul(n, -c), mul(u, s));
  const a1 = add(A, mul(m1, ra)), b1 = add(B, mul(m1, rb)), b2 = add(B, mul(m2, rb)), a2 = add(A, mul(m2, ra));
  const c1 = add(a1, mul(sub(b1, a1), t)), c2 = add(a2, mul(sub(b2, a2), t));
  const swA = cross(m2, mul(u, -1)) > 0 ? 1 : 0;
  return `M${P(a1)}L${P(c1)}L${P(c2)}L${P(a2)}A${r1(ra)} ${r1(ra)} 0 ${s >= 0 ? 1 : 0} ${swA} ${P(a1)}Z`;
}
// the smooth outline as a dense polygon, so it can be cut exactly where the waistband sits
function sampleCR(pts, per = 10) {
  const n = pts.length, o = [];
  for (let i = 0; i < n; i++) {
    const p0 = pts[(i - 1 + n) % n], p1 = pts[i], p2 = pts[(i + 1) % n], p3 = pts[(i + 2) % n];
    const c1 = add(p1, mul(sub(p2, p0), 1 / 6)), c2 = sub(p2, mul(sub(p3, p1), 1 / 6));
    for (let k = 0; k < per; k++) {
      const t = k / per, it = 1 - t;
      o.push([it*it*it*p1[0] + 3*it*it*t*c1[0] + 3*it*t*t*c2[0] + t*t*t*p2[0], it*it*it*p1[1] + 3*it*it*t*c1[1] + 3*it*t*t*c2[1] + t*t*t*p2[1]]);
    }
  }
  return o;
}
// keep the part of a polygon where f(p) >= 0 (f linear)
function clipHalf(poly, f) {
  const o = [];
  for (let i = 0; i < poly.length; i++) {
    const a = poly[i], b = poly[(i + 1) % poly.length], fa = f(a), fb = f(b);
    if (fa >= 0) o.push(a);
    if ((fa >= 0) !== (fb >= 0)) { const t = fa / (fa - fb); o.push([lerp(a[0], b[0], t), lerp(a[1], b[1], t)]); }
  }
  return o;
}
const WAIST = 0.25, HEM = 0.5;
const TORSO_SIDE_DENSE = sampleCR(TORSO_SIDE);
const SHORTS_SIDE_POLY = clipHalf(TORSO_SIDE_DENSE, p => WAIST - p[0]);

// two-bone leg: hip to ankle, knee on the side of pref. Returns thigh and shin angles.
const angOf = v => Math.atan2(v[0], -v[1]) / D2R;
function legIK(hip, ank, pref) {
  const LL = B.thigh + B.shin, v = sub(ank, hip), d = clamp(len(v), 10, LL - 0.05), u = nrm(v);
  const A = Math.acos(clamp((B.thigh ** 2 + d * d - B.shin ** 2) / (2 * B.thigh * d), -1, 1));
  const k1 = add(hip, mul(rot(u, A), B.thigh)), k2 = add(hip, mul(rot(u, -A), B.thigh));
  const knee = dot(sub(k1, hip), pref) >= dot(sub(k2, hip), pref) ? k1 : k2;
  return { thigh: angOf(sub(knee, hip)), shin: angOf(sub(ank, knee)), knee };
}
// interior angle at joint B of A-B-C, degrees
const jointAngle = (A, Bj, C) => Math.acos(clamp(dot(nrm(sub(A, Bj)), nrm(sub(C, Bj))), -1, 1)) / D2R;
function protractor(Bj, A, C, r) {
  const a = nrm(sub(A, Bj)), c = nrm(sub(C, Bj)), p1 = add(Bj, mul(a, r)), p2 = add(Bj, mul(c, r));
  return `M${P(p1)}A${r} ${r} 0 0 ${cross(a, c) > 0 ? 1 : 0} ${P(p2)}`;
}

/* Emit the side-view body as paint elements, far side first.
   hooks: {back, afterFar, afterTorso, beforeNearArm, front} arrays of elements
   mus: {name: {o, glow}} ; ghost: outline only */
function drawSide(J, mus, hooks = {}, ghost = false) {
  ghost = ghost || !!(mus && mus.__ghost);
  const K = painter(mus, ghost), out = K.out;
  if (!ghost) (hooks.back || []).forEach(e => out.push(e));

  const leg = (s, far) => {
    const hip = J.hip, knee = J["knee" + s], ankle = J["ankle" + s];
    const c = far ? "far" : "body";
    K.shaded(capsule(hip, knee, 9.4, 5.8), c, hip, knee, 9.4);
    const shinFill = ghost ? "" : K.across(c, knee, ankle, 5.8);
    K.part(capsule(knee, ankle, 5.8, 3.6), c, shinFill);
    if (!ghost) K.part(spindle(knee, ankle, 5.8, 3.6, 0.07, 0.6, -1, 1.15, 0.62), c + " calf", shinFill); // calf shares the shin's shading
    K.shaded(capsule(J["heel" + s], J["toe" + s], 4.2, 2.6), c, J["heel" + s], J["toe" + s], 4.2);
    if (!ghost) K.shaded(capsuleCut(hip, knee, 10.1, 6.5, HEM), far ? "shorts-far" : "shorts", hip, knee, 10);
    if (!far) {
      K.muscle("quads", spindle(hip, knee, 9.4, 5.8, 0.16, 0.94, 1));
      K.muscle("hams", spindle(hip, knee, 9.4, 5.8, 0.22, 0.9, -1));
      K.muscle("calves", spindle(knee, ankle, 5.8, 3.6, 0.07, 0.6, -1, 1.15, 0.62));
    }
  };
  const arm = (s, far) => {
    const c = far ? "far" : "body";
    const S = J.shoulder, E = J["elbow" + s], W = J["wrist" + s], Ge = J["handEnd" + s];
    K.shaded(capsule(S, E, 6.1, 4.2), c, S, E, 6.1);
    K.shaded(capsule(E, W, 4.2, 3.1), c, E, W, 4.2);
    K.shaded(capsule(W, Ge, 3.3, 3.1), c, W, Ge, 3.3);
    if (!far) {
      K.muscle("delts", spindle(S, E, 6.1, 4.2, -0.08, 0.46, 0, 1.1));
      K.muscle("reardelt", spindle(S, E, 6.1, 4.2, -0.04, 0.42, -1, 1.1));
      K.muscle("biceps", spindle(S, E, 6.1, 4.2, 0.28, 0.92, 1));
      K.muscle("triceps", spindle(S, E, 6.1, 4.2, 0.18, 0.9, -1));
      K.muscle("frontdelt", spindle(S, E, 6.1, 4.2, -0.06, 0.4, 1, 1.1));
      K.muscle("forearms", spindle(E, W, 4.2, 3.1, 0.04, 0.8, 0, 1.1));
    }
  };
  const FAR = J.farOff || [-2.8, 0];
  // far limbs, nudged up and back for depth
  const farStart = out.length;
  arm("F", true); leg("F", true);
  if (!ghost) {
    const g = out.splice(farStart);
    out.push({ tag: "g", a: { transform: `translate(${FAR[0]} ${FAR[1]})` }, kids: g });
  }
  if (!ghost) (hooks.afterFar || []).forEach(e => out.push(e));
  // neck, torso, shorts
  K.shaded(capsule(J.neck, J.head, 4.6, 4.4), "body", J.neck, J.head, 4.6);
  const top = J.T([1, 0]);
  K.shaded(blob(TORSO_SIDE.map(J.T)), "body", J.hip, top, 12);
  if (!ghost) K.part(poly(SHORTS_SIDE_POLY.map(J.T)), "shorts shorts-top", K.across("shorts", J.hip, top, 12));
  for (const k in MUS_SIDE) K.muscle(k, blob(MUS_SIDE[k].map(J.T)));
  // head: bald, lit like a sphere
  K.part(blob(HEAD.map(J.H)), "body", ghost ? "" : K.radial("body", J.H([1.5, 0]), 11));
  if (!ghost) {
    const ec = J.H([-1.6, 0.6]);
    out.push({ tag: "ellipse", a: { cx: r1(ec[0]), cy: r1(ec[1]), rx: 1.5, ry: 2.4, transform: `rotate(${r1(J.headA)} ${r1(ec[0])} ${r1(ec[1])})`, class: "ear" } });
  }
  if (!ghost) (hooks.afterTorso || []).forEach(e => out.push(e));
  leg("N", false);
  if (!ghost) (hooks.beforeNearArm || []).forEach(e => out.push(e));
  arm("N", false);
  if (!ghost) (hooks.front || []).forEach(e => out.push(e));
  return K.defs.concat(out);
}

/* ---------------- front view ---------------- */
const TORSO_FRONT_R = [[4,-0.12],[12.4,-0.07],[15.3,0.07],[13.9,0.24],[12.6,0.42],[14.2,0.6],[16.2,0.78],[19.4,0.92],[18.6,0.99],[11,1.03],[5.4,1.07]];
const TORSO_FRONT = TORSO_FRONT_R.concat(TORSO_FRONT_R.slice().reverse().map(([x, a]) => [-x, a]));
// front torso outline is [across, along]; cut the shorts at the waistband
const SHORTS_FRONT_POLY = clipHalf(sampleCR(TORSO_FRONT), p => (WAIST - 0.01) - p[1]);

function solveFront(p) {
  const J = {};
  const H = p.anchor; // hip centre
  J.hip = H;
  const TF = ([x, a]) => [H[0] + x, H[1] - a * B.trunk];
  J.TF = TF;
  for (const [s, sg] of [["R", 1], ["L", -1]]) {
    const hj = [H[0] + sg * 8.6, H[1]];
    const knee = add(hj, mul(dir(180 - sg * 2.5), B.thigh));
    const ankle = add(knee, mul(dir(180 - sg * 0.5), B.shin));
    J["hip" + s] = hj; J["knee" + s] = knee; J["ankle" + s] = ankle;
    const sh = [H[0] + sg * 17.5, H[1] - B.sh];
    J["sh" + s] = sh;
    const ua = 180 - sg * p.abd, fa = ua + sg * p.bend * (p.abd / 90);
    J["elbow" + s] = add(sh, mul(dir(ua), B.ua));
    J["wrist" + s] = add(J["elbow" + s], mul(dir(fa), B.fa));
    J["grip" + s] = add(J["elbow" + s], mul(dir(fa), B.grip));
    J["faDir" + s] = dir(fa);
  }
  J.neck = [H[0], H[1] - B.neck];
  J.head = [H[0], H[1] - B.neck - 19];
  J.shoulderY = H[1] - B.sh;
  return J;
}
function drawFront(J, mus, hooks = {}, ghost = false) {
  ghost = ghost || !!(mus && mus.__ghost);
  const K = painter(mus, ghost), out = K.out;
  for (const s of ["R", "L"]) {
    const sg = s === "R" ? 1 : -1;
    K.shaded(capsule(J["hip" + s], J["knee" + s], 9.2, 6), "body", J["hip" + s], J["knee" + s], 9.2);
    K.shaded(capsule(J["knee" + s], J["ankle" + s], 6, 3.8), "body", J["knee" + s], J["ankle" + s], 6);
    const a = J["ankle" + s], f1 = add(a, [-sg * 1.5, 5.2]), f2 = add(a, [sg * 4.5, 6.4]);
    K.shaded(capsule(f1, f2, 3.8, 3), "body", f1, f2, 3.8);
  }
  const ntop = add(J.head, [0, 4]);
  K.shaded(capsule(J.neck, ntop, 5.2, 5), "body", J.neck, ntop, 5.2);
  const tt = J.TF([0, 1]);
  K.shaded(blob(TORSO_FRONT.map(J.TF)), "body", J.hip, tt, 17);
  if (!ghost) {
    // one gradient for the whole garment so the pieces merge without a seam
    const sf = K.across("shorts", J.hip, tt, 17);
    for (const s of ["R", "L"]) K.part(capsuleCut(J["hip" + s], J["knee" + s], 10.1, 6.8, HEM), "shorts", sf);
    K.part(poly(SHORTS_FRONT_POLY.map(J.TF)), "shorts shorts-top", sf);
    // soft centre line and collarbones, drawn as cuts
    const c = J.TF;
    K.part(`M${P(c([0,0.92]))}L${P(c([0,0.46]))}M${P(c([-4,0.97]))}Q${P(c([-10,0.95]))} ${P(c([-15,0.95]))}M${P(c([4,0.97]))}Q${P(c([10,0.95]))} ${P(c([15,0.95]))}`, "", "fill:none;stroke:var(--plate);stroke-width:1.1;opacity:.7");
  }
  // head: bald, lit like a sphere
  const h = J.head;
  if (!ghost) for (const sg of [1, -1]) out.push({ tag: "ellipse", a: { cx: r1(h[0] + sg * 9.2), cy: r1(h[1] + 0.8), rx: 1.7, ry: 3, class: "ear" } });
  out.push({ tag: "ellipse", a: { cx: r1(h[0]), cy: r1(h[1]), rx: 9.2, ry: 11.2, class: ghost ? "ghost" : "body", style: ghost ? "" : K.radial("body", add(h, [1.5, -2]), 11) } });
  // arms
  for (const s of ["R", "L"]) {
    const S = J["sh" + s], E = J["elbow" + s], W = J["wrist" + s], G = add(J["grip" + s], mul(J["faDir" + s], 1.5));
    K.shaded(capsule(S, E, 6.4, 4.3), "body", S, E, 6.4);
    K.shaded(capsule(E, W, 4.3, 3.2), "body", E, W, 4.3);
    K.shaded(capsule(W, G, 3.4, 3.1), "body", W, G, 3.4);
    K.muscle("delts", spindle(S, E, 6.4, 4.3, -0.1, 0.5, 0, 1.25));
  }
  if (!ghost) (hooks.front || []).forEach(e => out.push(e));
  return K.defs.concat(out);
}

/* =========================================================
   Equipment helpers
   ========================================================= */
const el = (tag, a, text) => ({ tag, a, text });
const pth = (d, cls, style) => el("path", { d, class: cls, style: style || "" });
function rectPath(c, w, h, ang = 0) {
  const u = [Math.cos(ang * D2R), Math.sin(ang * D2R)], v = [-u[1], u[0]];
  const pts = [[-w / 2, -h / 2], [w / 2, -h / 2], [w / 2, h / 2], [-w / 2, h / 2]].map(([x, y]) => add(c, add(mul(u, x), mul(v, y))));
  return poly(pts);
}
function roundRect(x, y, w, h, r = 1.5) {
  return `M${r1(x + r)} ${r1(y)}H${r1(x + w - r)}Q${r1(x + w)} ${r1(y)} ${r1(x + w)} ${r1(y + r)}V${r1(y + h - r)}Q${r1(x + w)} ${r1(y + h)} ${r1(x + w - r)} ${r1(y + h)}H${r1(x + r)}Q${r1(x)} ${r1(y + h)} ${r1(x)} ${r1(y + h - r)}V${r1(y + r)}Q${r1(x)} ${r1(y)} ${r1(x + r)} ${r1(y)}Z`;
}
// rectangle whose long side runs along a direction vector
const rectAlong = (c, axis, along, across) => rectPath(c, along, across, Math.atan2(axis[1], axis[0]) / D2R);
// side-on dumbbell, handle horizontal through c
function dumbbellSide(c, cls, heads = 18) {
  return [
    pth(rectPath(c, 14, 3.4), cls),
    pth(roundRect(c[0] - 16, c[1] - heads / 2, 8.5, heads, 1.6), cls),
    pth(roundRect(c[0] + 7.5, c[1] - heads / 2, 8.5, heads, 1.6), cls),
  ];
}
// side-on dumbbell rotated: handle along unit vector u (2D)
function dumbbellAlong(c, u, cls, heads = 18) {
  const n = [-u[1], u[0]], at = (a, b) => add(c, add(mul(u, a), mul(n, b)));
  const plate = k => poly([at(k - 4.25, -heads / 2), at(k + 4.25, -heads / 2), at(k + 4.25, heads / 2), at(k - 4.25, heads / 2)]);
  return [pth(poly([at(-7, -1.7), at(7, -1.7), at(7, 1.7), at(-7, 1.7)]), cls), pth(plate(-11.75), cls), pth(plate(11.75), cls)];
}
// hex dumbbell seen end-on
function hexEnd(c, r, cls) {
  const pts = []; for (let i = 0; i < 6; i++) { const a = (i * 60 + 30) * D2R; pts.push([c[0] + r * Math.cos(a), c[1] + r * Math.sin(a)]); }
  return [pth(poly(pts), cls), pth(circle(c, r * 0.32), "line-dim")];
}
function floorEls(y, x0, x1, shift = 0) {
  const e = [el("line", { x1: x0, y1: y, x2: x1, y2: y, class: "floor" })];
  let d = "";
  const st = 10, off = ((shift % st) + st) % st;
  for (let x = x0 - st + off; x <= x1; x += st) {
    if (x < x0) continue;
    const big = Math.round((x - off) / st) % 5 === 0;
    d += `M${r1(x)} ${y + 1}V${y + (big ? 6 : 3)}`;
  }
  e.push(pth(d, "tick"));
  return e;
}
// soft contact shadow on the floor
const floorShadow = (ctx, cx, y, rx, o = 1, flat = 0.13) => el("ellipse", { cx: r1(cx), cy: r1(y), rx: r1(rx), ry: r1(rx * flat), fill: `url(#fs${ctx.uid})`, style: `opacity:${o}` });
const cueLine = (a, b, on) => pth(line(a, b), "cue" + (on ? " on" : ""));
const SVGNS = "http://www.w3.org/2000/svg";
function paint(parent, els) {
  const kids = parent.childNodes;
  let rebuild = kids.length !== els.length;
  if (!rebuild) for (let i = 0; i < els.length; i++) if (kids[i].nodeName !== els[i].tag) { rebuild = true; break; }
  if (rebuild) {
    while (parent.firstChild) parent.removeChild(parent.firstChild);
    for (const e of els) parent.appendChild(make(e));
    return;
  }
  for (let i = 0; i < els.length; i++) update(kids[i], els[i]);
}
function make(e) {
  const n = document.createElementNS(SVGNS, e.tag);
  n._a = {};
  update(n, e);
  return n;
}
function update(n, e) {
  for (const k in e.a) { const v = e.a[k]; if (n._a[k] !== v) { n.setAttribute(k, v); n._a[k] = v; } }
  if (e.text != null && n.textContent !== e.text) n.textContent = e.text;
  if (e.kids) paint(n, e.kids);
}

/* =========================================================
   3D body, orthographic, for front views of bent-over and
   horizontal bodies. World: x right, y up, z toward camera, cm.
   Capsules project to capsules exactly under orthographic
   projection, so limbs reuse the 2D capsule outline. The torso
   is a stack of elliptical cross-sections; consecutive pairs are
   hulled and the union is drawn as one silhouette.
   ========================================================= */
const a3 = (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const s3 = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const m3 = (a, k) => [a[0] * k, a[1] * k, a[2] * k];
const d3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const x3 = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const l3 = a => Math.hypot(a[0], a[1], a[2]);
const n3 = a => { const l = l3(a) || 1; return [a[0] / l, a[1] / l, a[2] / l]; };
const mix3 = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
// rotate unit vector u toward unit vector v by deg (v made perpendicular to u first)
function tilt3(u, v, deg) {
  const p = n3(s3(v, m3(u, d3(v, u)))), r = deg * D2R;
  return n3(a3(m3(u, Math.cos(r)), m3(p, Math.sin(r))));
}

// camera: straight on from the front, raised by elev degrees and looking down.
// x0, floorY place world (0,0,0) on the 2D page; the figure frame does the rest.
// yaw turns the camera around the body (degrees, positive swings toward the body's right side)
function camera3(elev, x0 = 150, floorY = 260, yaw = 0) {
  const c = Math.cos(elev * D2R), s = Math.sin(elev * D2R);
  const cy = Math.cos(yaw * D2R), sy = Math.sin(yaw * D2R);
  const X = p => p[0] * cy + p[2] * sy, Z = p => -p[0] * sy + p[2] * cy;
  return {
    elev, yaw,
    P: p => [x0 + X(p), floorY - (p[1] * c - Z(p) * s)],
    depth: p => p[1] * s + Z(p) * c,
    // the direction from the body toward the camera
    toCam: [-sy * c, s, cy * c],
  };
}

// two-bone IK in 3D: mid joint on the side of pole
function ik3(A, C, L1, L2, pole) {
  const v = s3(C, A), u = n3(v);
  const d = clamp(l3(v), Math.abs(L1 - L2) + 0.5, L1 + L2 - 0.05);
  const a = (L1 * L1 + d * d - L2 * L2) / (2 * d), h = Math.sqrt(Math.max(0, L1 * L1 - a * a));
  const pv = n3(s3(pole, m3(u, d3(pole, u))));
  const M = a3(A, a3(m3(u, a), m3(pv, h)));
  return { mid: M, end: a3(M, m3(n3(s3(C, M)), L2)) };
}
const angle3 = (A, Bj, C) => Math.acos(clamp(d3(n3(s3(A, Bj)), n3(s3(C, Bj))), -1, 1)) / D2R;

// cross-sections: [t along trunk, half width, half depth, front offset]
const TORSO_3D = [
  [-0.14, 12.6, 9.4, -1.6], [-0.02, 15.2, 11.2, -1.2], [0.12, 14.6, 10.8, -0.6], [0.25, 13.4, 9.8, 0],
  [0.42, 13.0, 9.6, 0], [0.6, 14.6, 10.6, 0.3], [0.78, 16.8, 11.2, 0.4], [0.9, 18.8, 9.8, -0.4],
  [0.97, 17.2, 7.6, -1.2], [1.03, 11.5, 5.6, -1.5],
];

/* Solve a body from a spec.
   spec.pelvis [x,y,z]; spec.spine unit-ish vector hip->shoulders; spec.lat hint (default +x);
   spec.head: degrees of neck extension (crown tips back) ;
   spec.arms.R/L: { at, pole, wrist?: bool, hand?: dir } ; at = grip point, or wrist point when wrist:true
   spec.legs.R/L: { ankle, pole, foot: heel->toe direction, sole: sole normal pointing down out of the foot } */
function solve3(spec) {
  const s = n3(spec.spine), latH = spec.lat || [1, 0, 0];
  const lat = n3(s3(latH, m3(s, d3(latH, s)))), ant = x3(lat, s);
  const P0 = spec.pelvis;
  // spec.curl: spinal flexion in degrees, spread evenly from pelvis to neck (constant curvature).
  // Positive curls the trunk toward the front (a crunch). The pelvis itself does not move.
  const k = (spec.curl || 0) * D2R;
  const sAt = t => (Math.abs(k) < 1e-4 ? s : n3(a3(m3(s, Math.cos(k * t)), m3(ant, Math.sin(k * t)))));
  const aAt = t => (Math.abs(k) < 1e-4 ? ant : n3(s3(m3(ant, Math.cos(k * t)), m3(s, Math.sin(k * t)))));
  const C = t => (Math.abs(k) < 1e-4 ? m3(s, t * B.trunk)
    : a3(m3(s, B.trunk * Math.sin(k * t) / k), m3(ant, B.trunk * (1 - Math.cos(k * t)) / k)));
  const T = (t, l, a) => a3(P0, a3(C(t), a3(m3(lat, l), m3(aAt(t), a))));
  const J = { s, lat, ant, T, aAt, pelvis: P0, sTop: sAt(1), antTop: aAt(1) };
  // spec.headBack: pull the head straight back (cm), as when a bar passes the face
  J.neck = a3(T(B.neck / B.trunk, 0, -1), m3(J.antTop, -(spec.headBack || 0)));
  J.headDir = tilt3(J.sTop, m3(J.antTop, -1), spec.head || 0);
  J.head = a3(J.neck, m3(J.headDir, 17));
  for (const [S, sg] of [["R", 1], ["L", -1]]) {
    J["sh" + S] = a3(T(B.sh / B.trunk, sg * 17.5, 0), m3(J.sTop, spec.shrug || 0));
    J["hip" + S] = T(0, sg * 8.6, 0);
  }
  J.shoulder = mix3(J.shR, J.shL, 0.5);
  const ARMS = typeof spec.arms === "function" ? spec.arms(J) : spec.arms;
  for (const [S, sg] of [["R", 1], ["L", -1]]) {
    void sg;
    const arm = ARMS[S];
    const L2 = arm.wrist ? B.fa : B.grip;
    // arm.elbow: a designed elbow (lengths already exact), so no IK and no flip near straight
    const r = arm.elbow ? { mid: arm.elbow, end: a3(arm.elbow, m3(n3(s3(arm.at, arm.elbow)), L2)) } : ik3(J["sh" + S], arm.at, B.ua, L2, arm.pole);
    J["elbow" + S] = r.mid;
    const fu = n3(s3(r.end, r.mid));
    J["wrist" + S] = a3(r.mid, m3(fu, B.fa));
    if (arm.wrist) { J["grip" + S] = a3(J["wrist" + S], m3(arm.hand, 5)); J["handEnd" + S] = a3(J["wrist" + S], m3(arm.hand, 9)); }
    else { J["grip" + S] = r.end; J["handEnd" + S] = a3(r.end, m3(fu, 2)); }
    const leg = spec.legs[S];
    // leg.knee: a designed knee (lengths already exact), so no IK
    const q = leg.knee ? { mid: leg.knee, end: a3(leg.knee, m3(n3(s3(leg.ankle, leg.knee)), B.shin)) } : ik3(J["hip" + S], leg.ankle, B.thigh, B.shin, leg.pole);
    J["knee" + S] = q.mid; J["ankle" + S] = q.end;
    const fd = n3(leg.foot), dn = n3(leg.sole || [0, -1, 0]);
    J["heel" + S] = a3(q.end, a3(m3(fd, -2.5), m3(dn, 4.2)));
    J["toe" + S] = a3(q.end, a3(m3(fd, 14), m3(dn, 5.6)));
  }
  J.shoulder = mix3(J.shR, J.shL, 0.5);
  return J;
}

// convex hull, monotone chain
function hull2(pts) {
  const p = pts.slice().sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  if (p.length < 3) return p;
  const cr = (o, a, b) => (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
  const lo = [], up = [];
  for (const q of p) { while (lo.length >= 2 && cr(lo[lo.length - 2], lo[lo.length - 1], q) <= 0) lo.pop(); lo.push(q); }
  for (let i = p.length - 1; i >= 0; i--) { const q = p[i]; while (up.length >= 2 && cr(up[up.length - 2], up[up.length - 1], q) <= 0) up.pop(); up.push(q); }
  up.pop(); lo.pop();
  return lo.concat(up);
}

/* Paint a solved 3D body. Everything is a depth-sorted item; extra items
   (equipment, cues that should be occluded) come in through `items` as
   { depth, els }. mus muscle names may be suffixed with R / L to light
   one side only (e.g. tricepsR); unsuffixed names light both sides. */
function draw3D(J, cam, mus, items = [], ghost = false) {
  ghost = ghost || !!(mus && mus.__ghost);
  const K = painter(mus, ghost), list = [];
  const P = cam.P, D = cam.depth;
  const item = (depth, fn, tag) => list.push({ depth, fn, tag });
  const musOn = (name, S) => (mus[name + S] ? name + S : mus[name] ? name : null);
  // side-on (sagittal plane facing the camera): use the 2D side profiles for torso,
  // head and muscles so these figures match the flat side-view ones exactly
  const sideOn = Math.abs(d3(J.lat, cam.toCam)) > 0.9;
  const farOf = S => d3(m3(J.lat, S === "R" ? 1 : -1), cam.toCam) < -0.7;
  const face = n3(x3(J.lat, J.headDir));
  const out3s = S => m3(J.lat, S === "R" ? 1 : -1);
  // which flank (+1/-1, in spindle terms) of the projected segment A-B faces world direction w
  const sideTo = (A, Bp, w) => { const u = nrm(sub(Bp, A)), nn = [u[1], -u[0]], q = sub(P(a3(J.pelvis, m3(w, 10))), P(J.pelvis)); return dot(nn, q) >= 0 ? 1 : -1; };

  // torso: sections -> projected ellipses -> hulled bands
  const secs = TORSO_3D.map(([t, w, dd, ao]) => {
    const c = J.T(t, 0, ao), pts = [];
    for (let i = 0; i < 18; i++) {
      const ph = (i / 18) * Math.PI * 2;
      pts.push(P(a3(c, a3(m3(J.lat, w * Math.cos(ph)), m3(J.aAt(t), dd * Math.sin(ph))))));
    }
    return { t, c, pts };
  });
  const bands = [];
  for (let i = 0; i < secs.length - 1; i++) {
    const a = secs[i], b = secs[i + 1];
    bands.push({ d: poly(hull2(a.pts.concat(b.pts))), depth: (D(a.c) + D(b.c)) / 2, shorts: b.t <= WAIST + 1e-6 });
  }
  const torsoDepth = bands.reduce((s, b) => s + b.depth, 0) / bands.length;
  item(torsoDepth, () => {
    const pb = P(J.pelvis), pt = P(J.T(1, 0, 0));
    if (sideOn) {
      const T2 = ([a, x]) => P(J.T(a, 0, x));
      K.shaded(blob(TORSO_SIDE.map(T2)), "body", pb, pt, 12);
      if (!ghost) K.part(poly(SHORTS_SIDE_POLY.map(T2)), "shorts shorts-top", K.across("shorts", pb, pt, 12));
      for (const k in MUS_SIDE) K.muscle(k, blob(MUS_SIDE[k].map(T2)));
      return;
    }
    if (ghost) { K.part(poly(hull2([].concat(...secs.map(s => s.pts)))), "ghost"); return; }
    const skin = K.across("body", pb, pt, 17), cloth = K.across("shorts", pb, pt, 17);
    for (const b of bands) K.part(b.d, "", "fill:var(--plate);stroke:var(--plate);stroke-width:2.6;stroke-linejoin:round");
    for (const b of bands.slice().sort((x, y) => x.depth - y.depth)) K.part(b.d, "", (b.shorts ? cloth : skin) + ";stroke:none");
    // chest and abs, drawn only when the front faces the camera
    const front = J.aAt(0.8);
    if (d3(front, cam.toCam) > 0.2) {
      if (mus.chest) for (const sg of [1, -1]) K.muscle("chest", blob([[0.72, 2], [0.72, 12], [0.84, 15], [0.93, 11], [0.93, 2], [0.86, 1]].map(([t, l]) => P(J.T(t, sg * l, 10.4)))));
      if (mus.core) K.muscle("core", blob([[0.2, -6], [0.2, 6], [0.4, 8], [0.62, 7.5], [0.66, 0], [0.62, -7.5], [0.4, -8]].map(([t, l]) => P(J.T(t, l, 9.6)))));
    }
    // upper back, drawn only when the back faces the camera
    const back = m3(J.ant, -1);
    if (mus.midback && d3(back, cam.toCam) > 0.08) {
      const q = [[0.66, 0], [0.8, 9], [0.93, 7], [0.93, -7], [0.8, -9]].map(([t, l]) => P(J.T(t, l, -10.5)));
      K.muscle("midback", blob(q));
    }
  }, "torso");

  // neck and head
  item(D(J.neck) + 0.5, () => {
    const a = P(J.neck), b = P(a3(J.neck, m3(J.headDir, 8)));
    K.shaded(capsule(a, b, 5.4, 5.2), "body", a, b, 5.4);
    if (mus.neck || mus.neckBack) {
      const u = nrm(sub(b, a)), nn = [u[1], -u[0]], f2 = sub(P(a3(J.neck, face)), a), sd = dot(nn, f2) >= 0 ? 1 : -1;
      if (mus.neck) K.muscle("neck", spindle(a, b, 5.4, 5.2, -0.1, 1.05, sd, 1.3));
      if (mus.neckBack) K.muscle("neckBack", spindle(a, b, 5.4, 5.2, -0.1, 1.05, -sd, 1.3));
    }
  }, "neck");
  item(D(J.head), () => {
    if (sideOn) {
      const H3 = ([x, y]) => P(a3(J.head, a3(m3(face, x), m3(J.headDir, -y))));
      K.part(blob(HEAD.map(H3)), "body", ghost ? "" : K.radial("body", H3([1.5, 0]), 11));
      if (!ghost) { const e = H3([-1.6, 0.6]); out.push({ tag: "ellipse", a: { cx: r1(e[0]), cy: r1(e[1]), rx: 1.6, ry: 1.9, class: "ear" } }); }
      return;
    }
    if (!ghost) for (const sg of [1, -1]) {
      const e = P(a3(J.head, m3(J.lat, sg * 9.2)));
      out.push({ tag: "ellipse", a: { cx: r1(e[0]), cy: r1(e[1]), rx: 1.8, ry: 2.4, class: "ear" } });
    }
    const h0 = P(a3(J.head, m3(J.headDir, -2))), h1 = P(a3(J.head, m3(J.headDir, 2)));
    K.part(capsule(h0, h1, 9.4, 9.4), "body", ghost ? "" : K.radial("body", add2(P(J.head), [1.5, -2]), 11));
  }, "head");

  // limbs, one item per segment
  for (const S of ["R", "L"]) {
    const sh = J["sh" + S], el_ = J["elbow" + S], wr = J["wrist" + S], he = J["handEnd" + S];
    const hip = J["hip" + S], kn = J["knee" + S], an = J["ankle" + S];
    const far = farOf(S), tone = far ? "far" : "body";
    const M = (name, d) => { const m = !far && musOn(name, S); if (m) K.muscle(m, d); };
    item((D(sh) + D(el_)) / 2, () => {
      const A = P(sh), Bp = P(el_);
      K.shaded(capsule(A, Bp, 6.4, 4.3), tone, A, Bp, 6.4);
      M("delts", spindle(A, Bp, 6.4, 4.3, -0.1, 0.5, 0, 1.25));
      M("frontdelt", spindle(A, Bp, 6.4, 4.3, -0.06, 0.42, 0, 1.15));
      M("triceps", spindle(A, Bp, 6.4, 4.3, 0.2, 0.92, 0, 0.9));
      M("biceps", spindle(A, Bp, 6.4, 4.3, 0.28, 0.92, 0, 0.9));
    }, "uarm" + S);
    item((D(el_) + D(wr)) / 2, () => {
      const A = P(el_), Bp = P(wr);
      K.shaded(capsule(A, Bp, 4.3, 3.2), tone, A, Bp, 4.3);
      M("forearms", spindle(A, Bp, 4.3, 3.2, 0.04, 0.8, 0, 1.1));
    }, "farm" + S);
    item((D(wr) + D(he)) / 2 + 0.3, () => { const A = P(wr), Bp = P(he); K.shaded(capsule(A, Bp, 3.4, 3.1), tone, A, Bp, 3.4); }, "hand" + S);
    item((D(hip) + D(kn)) / 2, () => {
      const A = P(hip), Bp = P(kn);
      K.shaded(capsule(A, Bp, 9.2, 6), tone, A, Bp, 9.2);
      if (!ghost) K.shaded(capsuleCut(A, Bp, 10.1, 6.8, HEM), far ? "shorts-far" : "shorts", A, Bp, 10);
      const fwd = sideTo(A, Bp, J.ant), backSide = -fwd;
      M("quads", spindle(A, Bp, 9.2, 6, 0.16, 0.94, sideOn ? fwd : 0, sideOn ? 1 : 0.9));
      M("hams", spindle(A, Bp, 9.2, 6, 0.22, 0.9, sideOn ? backSide : 0, sideOn ? 1 : 0.9));
      M("abductors", spindle(A, Bp, 9.2, 6, -0.12, 0.42, sideTo(A, Bp, out3s(S)), 1.1));
    }, "thigh" + S);
    item((D(kn) + D(an)) / 2, () => {
      const A = P(kn), Bp = P(an);
      K.shaded(capsule(A, Bp, 6, 3.8), tone, A, Bp, 6);
      if (sideOn) M("calves", spindle(A, Bp, 6, 3.8, 0.07, 0.6, -sideTo(A, Bp, J.ant), 1.15, 0.62));
    }, "shin" + S);
    item((D(J["heel" + S]) + D(J["toe" + S])) / 2, () => {
      const A = P(J["heel" + S]), Bp = P(J["toe" + S]);
      K.shaded(capsule(A, Bp, 3.8, 3), tone, A, Bp, 3.8);
    }, "foot" + S);
  }
  if (!ghost) for (const it of items) list.push({ depth: it.depth, fn: () => it.els.forEach(e => out.push(e)), tag: it.tag || "item" });

  const out = K.out;
  J._depths = {};
  for (const it of list) J._depths[it.tag] = it.depth;
  // a calibrated camera sorts by each part's average depth over the whole rep,
  // so overlapping parts never swap mid-motion (no popping)
  const key = it => (cam.avg && cam.avg[it.tag] != null ? cam.avg[it.tag] : it.depth);
  list.sort((a, b) => key(a) - key(b)).forEach(it => it.fn());
  J._order = list.map(it => it.tag);
  return K.defs.concat(out);
}
const add2 = add;

// average each part's depth over sample poses; draw3D then uses a fixed order
function calibrate3(cam, build, samples) {
  cam.avg = null;
  const sum = {}, n = {};
  for (const smp of samples) {
    const J = build(smp);
    for (const t in J._depths) { sum[t] = (sum[t] || 0) + J._depths[t]; n[t] = (n[t] || 0) + 1; }
  }
  cam.avg = {};
  for (const t in sum) cam.avg[t] = sum[t] / n[t];
}

const LIB = { B, D2R, EASE, HEAD, HEM, LIGHT, MUS_SIDE, P, SHORTS_FRONT_POLY, SHORTS_SIDE, SHORTS_SIDE_POLY, SVGNS, TONES, TORSO_3D, TORSO_FRONT, TORSO_FRONT_R, TORSO_SIDE, TORSO_SIDE_DENSE, WAIST, a3, add, add2, angOf, angle3, blob, calibrate3, camera3, capsule, capsuleCut, circle, clamp, clipHalf, cross, cueLine, d3, dir, dot, draw3D, drawFront, drawSide, dumbbellAlong, dumbbellSide, el, floorEls, floorShadow, frameOf, hexEnd, hull2, ik3, jointAngle, l3, legIK, len, lerp, lerpObj, line, m3, make, mix3, mul, n3, nrm, paint, painter, poly, protractor, pth, r1, rectAlong, rectPath, rot, roundRect, s3, sampleCR, soleY, solve3, solveFront, solveSide, spindle, sub, tilt3, update, x3 };
/* =========================================================
   Runtime: registry, mount, one shared animation loop.
   The app and the review gallery both go through mount(), so
   what gets reviewed is exactly what ships.
   ========================================================= */
const REG = {};
function define(fig) { REG[fig.id] = fig; }

const reduceMotion = () => !!(window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches);
let uidN = 0;
const live = new Set();
let rafId = 0, lastT = 0;
function tick(now) {
  rafId = 0;
  const dt = Math.min(0.05, (now - lastT) / 1000); lastT = now;
  let any = false;
  for (const c of live) {
    if (!c.box.isConnected) { live.delete(c); continue; }   // panel re-rendered underneath us
    if (c.playing && c.visible) { c.time += dt; c.draw(); any = true; }
  }
  if (any) rafId = requestAnimationFrame(tick);
}
function wake() { if (!rafId) { lastT = performance.now(); rafId = requestAnimationFrame(tick); } }

function sampleFig(fig, seq, total, t) {
  if (fig.procedural) {
    // procedural figures can still have several phases on the strip (lift, hold, lower)
    let tt = ((t % total) + total) % total, i = 0;
    while (i < seq.length - 1 && tt > seq[i].dur) { tt -= seq[i].dur; i++; }
    return { pose: null, phase: seq[i].label, pi: i, pt: clamp(tt / seq[i].dur, 0, 1), effort: seq[i].effort == null ? 1 : seq[i].effort, rep: Math.floor(t / total) };
  }
  let tt = t % total; const rep = Math.floor(t / total);
  for (let i = 0; i < seq.length; i++) {
    const p = seq[i];
    if (tt <= p.dur || i === seq.length - 1) {
      const x = clamp(tt / p.dur, 0, 1), e = (EASE[p.ease] || EASE.lin)(x);
      let pose;
      if (p.via) {
        // pass through the via key on a smooth curve (quadratic; control set so the midpoint lands on it)
        const A = fig.keys[p.from], V = fig.keys[p.via], Bk = fig.keys[p.to];
        const C = lerpObj(lerpObj(A, Bk, 0.5), V, 2);
        pose = lerpObj(lerpObj(A, C, e), lerpObj(C, Bk, e), e);
      } else pose = lerpObj(fig.keys[p.from], fig.keys[p.to], e);
      return { pose, phase: p.label, pi: i, pt: x, effort: p.effort, rep };
    }
    tt -= p.dur;
  }
}

const onlyGhost = els => {
  const o = [];
  for (const e of els) { if (e.kids) o.push(...onlyGhost(e.kids)); else if (e.a && e.a.class === "ghost") o.push(e); }
  return o;
};

/* mount(container, id, opts) -> controller | null
   Builds the figure box and the tempo strip inside container.
   opts.tempo (default true), opts.chrome (default true: corner marks and labels). */
function mount(container, id, opts = {}) {
  const fig = REG[id];
  if (!fig || !container) return null;
  const uid = "ff" + (++uidN);
  const seq = fig.procedural ? fig.seqLabels : fig.seq;
  const total = fig.procedural ? fig.period : seq.reduce((s, p) => s + p.dur, 0);
  const SVGNS = "http://www.w3.org/2000/svg";

  const wrap = document.createElement("div");
  wrap.className = "ffig-wrap";
  const box = document.createElement("div");
  box.className = "ffig-box";
  box.setAttribute("role", "img");
  box.tabIndex = 0;
  box.setAttribute("aria-label", `${opts.name || fig.name || fig.id} demonstration. Tap to pause.`);
  const svg = document.createElementNS(SVGNS, "svg");
  svg.setAttribute("class", "ffig");
  svg.setAttribute("viewBox", "0 0 300 300");
  svg.innerHTML = `
    <defs>
      <pattern id="${uid}grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="10" cy="10" r=".7" class="grid-dot"/></pattern>
      <radialGradient id="fs${uid}"><stop offset="0" stop-color="#000" stop-opacity=".6"/><stop offset=".6" stop-color="#000" stop-opacity=".22"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient>
    </defs>
    <rect width="300" height="300" fill="url(#${uid}grid)"/>
    <g class="world"><g class="ghostl"></g><g class="live"></g></g>
    <g class="labels"></g>
    ${opts.chrome === false ? "" : `<g>
      <path class="corner" d="M8 18V8H18M282 8H292V18M292 282V292H282M18 292H8V282"/>
      <text class="chrome" x="16" y="21">${opts.code || fig.code || ""}${(opts.code || fig.code) ? " · " : ""}${fig.id.toUpperCase()}</text>
      <text class="chrome" x="284" y="21" text-anchor="end">${fig.view}</text>
      <text class="chrome state" x="16" y="286"></text>
      <text class="chrome count" x="284" y="286" text-anchor="end"></text>
    </g>`}`;
  box.appendChild(svg);
  wrap.appendChild(box);
  let segs = [];
  if (opts.tempo !== false) {
    const tempo = document.createElement("div");
    tempo.className = "ffig-tempo";
    tempo.innerHTML = seq.map(p => `<div class="seg" style="flex:${p.dur} 1 auto"><i class="bar"><b></b></i><span class="lab"></span></div>`).join("");
    wrap.appendChild(tempo);
    segs = [...tempo.querySelectorAll(".seg")].map(s => ({ s, b: s.querySelector("b"), l: s.querySelector(".lab") }));
    segs.forEach((g, i) => g.l.textContent = fig.procedural ? seq[i].label : (seq.length > 4 ? seq[i].label : `${seq[i].label} ${seq[i].dur}s`));
  }
  container.appendChild(wrap);

  const world = svg.querySelector(".world"), liveG = svg.querySelector(".live"), ghostL = svg.querySelector(".ghostl");
  const labelsG = svg.querySelector(".labels"), stateT = svg.querySelector(".state"), countT = svg.querySelector(".count");
  const { k, cx, cy } = fig.frame;
  const ox = 150 - cx * k, oy = 150 - cy * k;
  world.setAttribute("transform", `translate(${r1(ox)} ${r1(oy)}) scale(${k})`);
  const toScreen = p => [ox + p[0] * k, oy + p[1] * k];

  const c = { fig, box, wrap, time: 0, playing: !reduceMotion(), visible: true, uid };
  const musFor = effort => {
    const m = { __id: uid };
    for (const name in fig.muscles) {
      const w = fig.muscles[name], prime = w >= 0.99;
      // halo is a soft stroke, not a blur filter: filters snap to whole pixels and made the shoulders shimmer
      m[name] = { o: r1(prime ? 0.4 + 0.6 * effort : (0.16 + 0.34 * effort) * (w / 0.55)), h: prime ? r1(0.34 * clamp((effort - 0.4) / 0.6, 0, 1)) : 0 };
    }
    return m;
  };
  c.draw = () => {
    let s, r;
    try {
      s = sampleFig(fig, seq, total, c.time);
      const ctx = { mus: musFor(s.effort), phase: s.phase, time: c.time, uid, pt: s.pt, pi: s.pi, seg: fig.procedural ? null : seq[s.pi], ghost: false };
      r = fig.build(s.pose, ctx);
    } catch (err) {
      // one bad figure must never take the Tips panel down with it
      c.failed = err; c.stop();
      if (opts.onError) opts.onError(err);
      return;
    }
    paint(liveG, r.els);
    c.lastJ = r.J;
    liveG.style.opacity = r.opacity == null ? "" : r1(r.opacity);
    if (!c.playing && !fig.noGhost) {
      try {
        let gr;
        if (fig.procedural) gr = fig.build(null, { mus: { __ghost: true, __id: uid + "g" }, phase: "", time: fig.ghostTime, uid, pt: 0, seg: null, ghost: true });
        else {
          const ph = seq[s.pi], near = ph.from === ph.to ? ph.from : (s.pt > 0.5 ? ph.to : ph.from);
          const gk = fig.ghostFor ? fig.ghostFor(near) : Object.keys(fig.keys).find(kk => kk !== near);
          const gseg = seq.find(q => q.to === gk) || seq[0];
          gr = fig.build(fig.keys[gk], { mus: { __ghost: true, __id: uid + "g" }, phase: gseg.label, time: 0, uid, pt: 1, seg: gseg, ghost: true });
        }
        paint(ghostL, onlyGhost(gr.els));
      } catch (e) { paint(ghostL, []); }
    } else if (ghostL.firstChild) paint(ghostL, []);
    const lab = [];
    for (const L of r.labels || []) {
      if (!L.text) continue;
      const p = toScreen(L.at);
      lab.push(el("text", { x: r1(p[0]), y: r1(p[1]), class: "lbl" + (L.on ? " on" : ""), "text-anchor": L.anchor || "start" }, L.text));
    }
    for (const Dd of r.dots || []) {
      const p = toScreen(Dd.at);
      lab.push(el("circle", { cx: r1(p[0]), cy: r1(p[1]), r: 2.6, class: "cue-dot" + (Dd.on ? " on" : "") }));
    }
    paint(labelsG, lab);
    if (stateT) stateT.textContent = c.playing ? "" : fig.noGhost ? "PAUSED" : "PAUSED · GHOST = OTHER END";
    if (countT) countT.textContent = r.count != null ? r.count : `REP ${String((s.rep % 99) + 1).padStart(2, "0")}`;
    segs.forEach((g, i) => {
      const w = i < s.pi ? 100 : i === s.pi ? s.pt * 100 : 0;
      g.b.style.width = w.toFixed(1) + "%";
      g.s.classList.toggle("on", i === s.pi);
    });
    if (fig.procedural && segs.length) segs.forEach((g, i) => { const want = i === s.pi && r.tempoLabel ? r.tempoLabel : seq[i].label; if (g.l.textContent !== want) g.l.textContent = want; });
  };
  c.play = () => { c.playing = true; wake(); c.draw(); };
  c.pause = () => { c.playing = false; c.draw(); };
  c.toggle = () => (c.playing ? c.pause() : c.play());
  c.stop = () => { c.playing = false; live.delete(c); if (c.io) c.io.disconnect(); };
  box.addEventListener("click", c.toggle);
  box.addEventListener("keydown", e => { if (e.key === " " || e.key === "Enter") { e.preventDefault(); c.toggle(); } });
  if ("IntersectionObserver" in window) {
    c.io = new IntersectionObserver(en => { c.visible = en[en.length - 1].isIntersecting; if (c.visible) wake(); }, { rootMargin: "80px" });
    c.io.observe(box);
  }
  // resting frame for reduced motion: the working end of the rep
  if (!c.playing) c.time = fig.procedural ? 0.3 : Math.max(0, seq.slice(0, seq.findIndex(p => p.to === fig.ghostKey) + 1).reduce((a, p) => a + p.dur, 0) - 0.01);
  live.add(c);
  c.draw();
  if (c.failed) { wrap.remove(); return null; }
  wake();
  return c;
}
function stopAll() { for (const c of live) c.stop(); live.clear(); }

window.ForgeFigures = {
  define, mount, stopAll,
  has: id => !!REG[id],
  get: id => REG[id],
  list: () => Object.keys(REG),
  _live: live,
  lib: LIB,
};

})();
